import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Wallet, verifyMessage, getAddress } from 'ethers';
import { createApp } from './server.mjs';

test('real signed HTTP sessions isolate wallet data, reject replay and store encrypted content',async()=>{
  const dataDir=await mkdtemp(path.join(os.tmpdir(),'consensus-bell-auth-'));
  const origin='http://127.0.0.1:52203',app=await createApp({dataDir,origin});
  await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
  const base='http://127.0.0.1:'+app.server.address().port;
  const request=async(url,options={})=>{const r=await fetch(base+url,{method:options.method||'GET',headers:{Origin:origin,'Content-Type':'application/json',...(options.cookie?{Cookie:options.cookie}:{}),...options.headers},body:options.body?JSON.stringify(options.body):undefined});return {status:r.status,cookie:r.headers.get('set-cookie'),body:await r.json()};};
  const alice=Wallet.createRandom(),bob=Wallet.createRandom();
  try {
    assert.equal((await request('/api/profile')).status,401);
    const c=await request('/api/auth/challenge',{method:'POST',body:{address:alice.address}});
    const bad=await request('/api/auth/verify',{method:'POST',body:{id:c.body.id,signature:await bob.signMessage(c.body.message)}});
    assert.equal(bad.status,401,'A different key cannot authenticate as Alice');
    const signature=await alice.signMessage(c.body.message);
    const a=await request('/api/auth/verify',{method:'POST',body:{id:c.body.id,signature}});
    assert.equal(a.status,200);assert.equal(a.body.address,alice.address);assert.match(a.cookie,/HttpOnly/);assert.match(a.cookie,/SameSite=Strict/);
    assert.equal((await request('/api/auth/verify',{method:'POST',body:{id:c.body.id,signature}})).status,401,'Nonce cannot be replayed');
    const cb=await request('/api/auth/challenge',{method:'POST',body:{address:bob.address}});
    const b=await request('/api/auth/verify',{method:'POST',body:{id:cb.body.id,signature:await bob.signMessage(cb.body.message)}});
    const profile={name:'User Alice',city:'Shanghai',gender:'Private',age:'20–26',interests:['Photography'],statement:'Private life, mutual choices.',intention:'Serious relationship',discoverable:false};
    assert.equal((await request('/api/profile',{method:'PUT',cookie:a.cookie,body:profile})).status,200);
    assert.equal((await request('/api/profile',{cookie:a.cookie})).body.profile.name,'User Alice');
    assert.equal((await request('/api/profile',{cookie:b.cookie})).body.profile,null,'Each wallet starts with its own profile');
    assert.equal((await request('/api/discover',{cookie:b.cookie})).body.length,0,'Private profile is not discoverable');
    assert.equal((await request('/api/profile',{method:'PUT',cookie:a.cookie,body:profile,headers:{Origin:'https://attacker.invalid'}})).status,403,'Foreign-origin mutation is rejected');
    const pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},false,['deriveKey']);
    const raw=await crypto.subtle.exportKey('jwk',pair.publicKey),key={kty:raw.kty,crv:raw.crv,x:raw.x,y:raw.y};
    const message=`Consensus Bell encryption key\nOrigin: ${origin}\nAddress: ${alice.address}\nPublic key: ${JSON.stringify(key)}`;
    assert.equal((await request('/api/key',{method:'PUT',cookie:a.cookie,body:{key,signature:await bob.signMessage(message)}})).status,403);
    const keySignature=await alice.signMessage(message);
    assert.equal((await request('/api/key',{method:'PUT',cookie:a.cookie,body:{key,signature:keySignature}})).status,200);
    globalThis.window={ethers:{verifyMessage,getAddress}};
    const {validateKey}=await import('./web/crypto.js');
    assert.deepEqual(validateKey({address:alice.address,key,signature:await alice.signMessage(message)},alice.address,origin),key);
    assert.throws(()=>validateKey({address:alice.address,key,signature:keySignature},bob.address,origin),/目标钱包/,'A valid certificate for another wallet cannot substitute the intended recipient');
    const aes=await crypto.subtle.deriveKey({name:'ECDH',public:pair.publicKey},pair.privateKey,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);
    const iv=crypto.getRandomValues(new Uint8Array(12)),content='The server must not see this private memory';
    const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},aes,new TextEncoder().encode(content));
    const body={scope:'personal',type:'note',iv:Buffer.from(iv).toString('base64'),ciphertext:Buffer.from(ciphertext).toString('base64')};
    const saved=await request('/api/memories',{method:'POST',cookie:a.cookie,body});assert.equal(saved.status,201);
    const stored=app.db.prepare('SELECT body FROM memories WHERE id=?').get(saved.body.id);assert.equal(stored.body.includes(content),false,'Database contains ciphertext, not memory plaintext');
    const own=await request('/api/memories',{cookie:a.cookie});assert.equal(own.body.length,1);
    const decoded=await crypto.subtle.decrypt({name:'AES-GCM',iv},aes,Buffer.from(own.body[0].body.ciphertext,'base64'));assert.equal(new TextDecoder().decode(decoded),content);
    assert.equal((await request('/api/memories',{cookie:b.cookie})).body.length,0,'Bob cannot read Alice’s private records');
    assert.equal((await request('/api/memories?id='+saved.body.id,{method:'DELETE',cookie:b.cookie})).status,403);
    assert.equal((await request('/api/memories?id='+saved.body.id,{method:'PUT',cookie:a.cookie,body})).status,200);
    assert.equal((await request('/api/ring',{cookie:a.cookie})).status,400,'Unconfigured chain does not invent a relation');
    assert.equal((await request('/api/transactions',{method:'POST',cookie:a.cookie,body:{hash:'0x'+'11'.repeat(32)}})).status,400,'Unconfigured chain does not invent a transaction confirmation');
    for(const url of ['/','/app.js','/view.js','/crypto.js','/complete.css','/ethers.js','/assets/ring-float.jpg'])assert.equal((await fetch(base+url)).status,200,url);
    assert.equal((await fetch(base+'/.env')).status,404,'Configuration files are not served');
    for(const type of ['goal','video'])assert.equal((await request('/api/memories',{method:'POST',cookie:a.cookie,body:{...body,type}})).status,201,'Encrypted '+type+' uses existing account ownership');
    assert.equal((await request('/api/memories',{cookie:b.cookie})).body.length,0,'Goals and video envelopes do not cross wallet boundaries');
    for(const url of ['/onboarding.js','/journey.js','/journey-actions.js','/journey.css'])assert.equal((await fetch(base+url)).status,200,url);
    assert.equal((await request('/api/logout',{method:'POST',cookie:a.cookie})).status,200);
    assert.equal((await request('/api/profile',{cookie:a.cookie})).status,401,'Logout revokes server session');
  }finally{await app.close();await rm(dataDir,{recursive:true,force:true});}
});
