import {text as e,icon} from './components.js';
const filterButton=(label,action,value,selected)=>`<button class="chip ${selected?'active':''}" data-action="${action}" data-value="${value}" aria-pressed="${selected}">${label}</button>`;
export function editorialStory(state,h,memories,privateHint,guest){
  const {head,btn,notice}=h,kind=state.storyFilter||'all',query=(state.storyQuery||'').trim().toLocaleLowerCase();
  const all=memories.filter(m=>['note','photo','video'].includes(m.type));
  const items=all.filter(m=>kind==='all'||m.type===kind).filter(m=>!query||[m.content?.title,m.content?.text].filter(Boolean).join(' ').toLocaleLowerCase().includes(query));
  const groups=new Map();for(const memory of items){const month=new Date(memory.at).toLocaleDateString('zh-CN',{year:'numeric',month:'long'});if(!groups.has(month))groups.set(month,[]);groups.get(month).push(memory);}
  return head('Our Story','All the moments, big or small.')+`<div class="bell-editorial-toolbar">${btn(icon('image')+' 记录片刻','memory','','compact')}${btn(icon('lock')+' Bell Vault','vault','','light compact')}</div><form class="bell-story-search" data-form="story-search"><label class="sr-only" for="story-query">搜索已读取的记忆</label><input id="story-query" name="query" maxlength="100" value="${e(state.storyQuery||'')}" placeholder="寻找一段记忆…"><button class="btn light compact" type="submit">搜索</button></form><div class="journey-filters" aria-label="记忆分类">${[['all','全部'],['photo','照片'],['video','视频'],['note','文字']].map(([value,label])=>filterButton(label+' · '+(value==='all'?all.length:all.filter(m=>m.type===value).length),'story-filter',value,kind===value)).join('')}</div>`+`<details class="card"><summary>${icon('lock')} 只属于你们的记忆</summary><p>${e(privateHint)}</p></details>`+[...groups].map(([month,rows])=>`<section class="story-month"><div class="row"><h2>${icon('clock')}${e(month)}</h2><span class="small muted">${rows.length} 个片刻</span></div><div class="bell-story-timeline">${rows.map(memory=>{
    const image=/^data:image\/(jpeg|png|webp);base64,/.test(memory.content?.image||'');
    return `<article class="bell-memory"><div class="bell-memory-date"><span>${new Date(memory.at).getDate().toString().padStart(2,'0')}</span><small>${e(new Date(memory.at).toLocaleDateString('zh-CN',{month:'short'}))}</small></div><div class="bell-memory-card"><div class="row"><span class="small muted">${icon(memory.type==='note'?'book':'image')}${e(guest?'未上传草稿':memory.owner?.slice(0,6)+'…'+memory.owner?.slice(-4))}</span><span class="pill">${icon('lock')}${guest?'本页草稿':'加密记忆'}</span></div><button class="title" data-action="memory-detail" data-id="${e(memory.id)}">${e(memory.content?.title||'加密记忆')}</button><p>${e(memory.content?.text?.slice(0,180)||memory.error||'')}</p>${image?`<button class="bell-memory-photo" data-action="memory-detail" data-id="${e(memory.id)}" aria-label="查看 ${e(memory.content?.title||'记忆照片')}"><img src="${e(memory.content.image)}" width="320" height="220" alt="${e(memory.content?.title||'记忆照片')}"></button>`:memory.type==='video'?'<span class="pill">视频 · 点击标题播放</span>':''}</div></article>`;
  }).join('')}</div></section>`).join('')+(!items.length?`<div class="bell-empty-art">${icon('book')}<h2>${query?'没有找到这段记忆':'让小小的日常，成为共同的故事'}</h2><p>${query?'只搜索已经获准读取并成功解密的标题与正文。试试别的词，或清空搜索。':'一张照片、一句心里话，或一次一起走过的路。'}</p>${query?btn('清空搜索','story-search-clear','','light'):btn('Record Moment · 记下一个片刻','memory','','rose')}</div>`:'');
}
export function editorialVows(state,h,memories,relation,guest){
  const {head,btn}=h,vows=relation?.vows||[],filter=state.vowFilter||'all',confirmed=vows.filter(v=>v.confirmed),pending=vows.filter(v=>!v.confirmed);
  const rows=filter==='confirmed'?confirmed:filter==='pending'?pending:vows;
  // Licensed local artwork; captions are aspirational design reference, never sample user records.
  const inspiration=[['vow-hero.webp','郑重的时刻','在一个认真准备的时刻，说出那句话'],['east-lake.webp','一起走过','把一次共同的远行，变成约定'],['cinema.webp','日常的浪漫','哪怕只是一部两个人的电影'],['anniversary.webp','重新选择','每年同一天，再选一次彼此']];
  const hero=`<figure class="bell-vows-hero"><img src="/assets/vow-hero.webp" width="720" height="400" fetchpriority="high" alt="玫瑰色调的誓言仪式意象"><figcaption><h1>Our Vows</h1><p>一次次约定，一次次选择彼此。</p></figcaption></figure>`;
  const gallery=`<section class="bell-vow-inspiration" aria-label="誓言灵感 · 设计示意"><div class="row"><h2>${icon('spark')} 誓言可以是什么样子</h2><span class="small muted">设计示意 · 不是用户记录</span></div><div class="bell-vow-gallery">${inspiration.map(([image,title,caption])=>`<figure><img src="/assets/${image}" width="300" height="400" loading="lazy" alt="${e(title)}意象"><figcaption><b>${e(title)}</b><small>${e(caption)}</small></figcaption></figure>`).join('')}</div></section>`;
  return hero+`<div class="bell-vow-summary"><div><strong>${guest||!relation?'—':vows.length}</strong><span>Total Vows · 全部誓言</span></div>${btn(icon('next')+' New Vow','new-vow','','compact')}</div><blockquote class="bell-vow-quote">“A thought becomes a Vow only when both of you choose it.”</blockquote><div class="journey-filters" aria-label="誓言状态">${[['all','全部',vows.length],['confirmed','已确认',confirmed.length],['pending','待确认',pending.length]].map(([value,label,count])=>filterButton(label+' · '+count,'vow-filter',value,filter===value)).join('')}</div><div class="bell-vow-list">${rows.map(vow=>{
    const memory=memories.find(m=>m.body?.hash?.toLowerCase()===vow.hash.toLowerCase());
    return `<button class="bell-vow-card" data-action="vow-detail" data-index="${vow.index}"><span class="bell-vow-number">${String(vow.index+1).padStart(2,'0')}</span><div><span class="pill ${vow.confirmed?'ok':'pending'}">${icon(vow.confirmed?'shield':'clock')}${vow.confirmed?'双方已确认':'等待另一位参与者确认'}</span><h2>${e(memory?.content?.text||vow.text||'加密正文暂不可读')}</h2><p>${vow.confirmed?'两次独立选择，成为真实的链上记录。':'可以查看正文并核对哈希，再由本人决定是否确认。'}</p></div>${icon('next')}</button>`;
  }).join('')}</div>`+(!rows.length?gallery+`<div class="bell-empty-art">${icon(filter==='confirmed'?'shield':'heart')}<h2>${filter==='pending'?'没有待确认的誓言':filter==='confirmed'?'还没有双方确认的誓言':'把一个想法，变成共同选择'}</h2><p>只有两人的真实确认，才会成为生效誓言。${guest?'登录并建立 Ring 后，写下的每一句都会加密保存、由双方各自签名确认。':''}</p>${filter==='all'?btn('写下一句誓言','new-vow','','rose'):btn('查看全部誓言','vow-filter','data-value="all"','light')}</div>`:'');
}
export function bondSummary(state,relation,goalCount){
  return `<section class="bell-bond-summary"><span>${icon('wallet')} Our shared contribution</span><strong>${relation?.balances?e(state.balance||'0'):'—'} <small>BOT</small></strong><p>${relation?.status==='ACTIVE'?'当前 Ring 的链上出资余额':'尚未读取活动 Ring 的链上余额'}</p><div><span>${goalCount} 份加密规划</span><span>${relation?.id&&relation.id!=='0'?'Ring #'+e(relation.id):'尚未建立 Ring'}</span></div></section>`;
}
