export const emptyProfile=()=>({name:'',city:'',gender:'',age:'',interests:[],statement:'',intention:'Serious relationship',discoverable:false,avatarUrl:'',occupation:''});
export const carryIdentityDraft=(existingProfile,visitorDraft)=>!existingProfile&&visitorDraft?{...visitorDraft,interests:[...(visitorDraft.interests||[])]}:null;
export const interestChoices=[['Music','音乐','in-music.webp'],['Travel','旅行','in-travel.webp'],['Photography','摄影','in-photo.webp'],['Food','美食','in-food.webp'],['Reading','阅读','in-reading.webp'],['Movies','电影','in-movies.webp'],['AI','AI','in-ai.webp'],['Art','艺术','in-art.webp'],['Sports','运动','in-sports.webp']];
export function updateIdentity(draft,step,fields){
  const next={...emptyProfile(),...draft,interests:[...(draft?.interests||[])]};
  if(step===1){for(const key of ['name','city','gender','age','avatarUrl','occupation'])next[key]=String(fields[key]||'').trim();if(!next.name)throw new Error('先告诉我们你的昵称。');if(next.name.length>40)throw new Error('昵称最多 40 个字。');if(next.avatarUrl&&!/^\/assets\/[a-zA-Z0-9._-]+$/.test(next.avatarUrl)){let ok=false;try{const u=new URL(next.avatarUrl);ok=u.protocol==='https:'&&!u.username&&!u.password;}catch{}if(!ok)throw new Error('头像链接必须是 HTTPS 图片地址（HTTPS only）。');}if(next.occupation.length>80)throw new Error('职业最多 80 个字。');}
  if(step===3)next.intention=String(fields.intention||next.intention).trim();
  if(step===4){next.statement=String(fields.statement||'').trim();next.discoverable=Boolean(fields.discoverable);if(next.statement.length>200)throw new Error('爱情宣言最多 200 个字。');}
  if(next.interests.length>8)throw new Error('最多选择八项兴趣。');return next;
}
// Stitch 02 原稿对齐的行内图标（16-18px 线性）
const SVG={
  heart:'<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 20.5l-7.2-7.2a4.6 4.6 0 1 1 7.2-5.6 4.6 4.6 0 1 1 7.2 5.6z"/></svg>',
  gender:'<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M12 12v7M9 19h6"/></svg>',
  location:'<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 21c4-4.4 6-7.4 6-10a6 6 0 1 0-12 0c0 2.6 2 5.6 6 10z"/><circle cx="12" cy="10.5" r="2"/></svg>',
  age:'<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" aria-hidden="true"><path d="M6 3h12M6 21h12M8 3v3.2a4 4 0 0 0 8 0V3M8 21v-3.2a4 4 0 0 1 8 0V21"/></svg>',
  spark:'<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8z"/></svg>',
  edit:'<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 20l4.5-1L20 7.5 16.5 4 5 15.5z"/></svg>',
  camera:'<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 8h3l2-2.5h6L17 8h3v11H4z"/><circle cx="12" cy="13" r="3.2"/></svg>',
  shield:'<svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3l7 3v5c0 4.5-3 8-7 10-4-2-7-5.5-7-10V6z"/><path d="M9 11.5l2 2 4-4"/></svg>',
  arrow:'<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h13M13 6.5L18.5 12 13 17.5"/></svg>',
};
const idRow=(label,name,value,attrs,icon)=>{
  return `<div class="id-row"><span class="ic">${SVG[icon]||SVG.spark}</span><label for="identity-${name}">${label}</label><input id="identity-${name}" name="${name}" value="${value}" ${attrs}><span class="ed" aria-hidden="true">${SVG.edit}</span></div>`;
};
export function onboardingView(state,{escape,head,submit,btn,avatar}){
  const step=state.identityStep||1,draft={...emptyProfile(),...state.identityDraft,...(state.profile||{})};
  const titles=['Tell us about you','What do you love?','What are you looking for?','Love, in your own words'];
  const subs=['从一个属于你的名字开始。','选择几件让你心动的事。','每一种开始，都值得认真对待。','不用完美，真诚就很好。'];
  let fields='';
  if(step===1)fields=`<div class="id-avatar-stage"><div class="id-avatar-ring">${draft.avatarUrl&&/^(https:\/\/|\/assets\/)/.test(draft.avatarUrl)?`<img src="${escape(draft.avatarUrl)}" alt="我的头像" referrerpolicy="no-referrer">`:`<span aria-hidden="true">${escape(Array.from(draft.name)[0]||'你')}</span>`}<label class="id-camera" aria-label="上传我的照片" title="上传我的照片"><input type="file" accept="image/*" data-avatar-file hidden>${SVG.camera}</label></div><button type="button" class="id-curate" data-action="avatar-picker">✦ Curate Photo · 挑选头像</button></div><input type="hidden" name="avatarUrl" value="${escape(draft.avatarUrl)}"><div class="id-rows">${idRow('昵称','name',draft.name,'required maxlength="40" autocomplete="nickname" placeholder="你希望被怎样称呼"','heart')}${idRow('职业 · 可选','occupation',draft.occupation,'maxlength="80" placeholder="你在做什么"','spark')}${idRow('性别 · 可选','gender',draft.gender,'maxlength="30" placeholder="由你定义"','gender')}${idRow('城市','city',draft.city,'maxlength="60" autocomplete="address-level2" placeholder="你生活的地方"','location')}${idRow('年龄 · 可选','age',draft.age,'maxlength="30" placeholder="例如 20–26"','age')}</div><div class="id-note">${SVG.shield}<span>你的身份资料在双方建立共鸣前保持私密；保存后随时可修改。</span></div>`;
  if(step===2)fields=`<div class="interest-grid">${interestChoices.map(([value,label,image])=>`<button type="button" class="interest ${draft.interests.includes(value)?'selected':''}" data-action="identity-interest" data-value="${value}" aria-pressed="${draft.interests.includes(value)}"><img src="/assets/${image}" width="160" height="108" alt=""><span>${label}<small>${value}</small></span></button>`).join('')}</div><p class="small muted center">已选择 ${draft.interests.length}/8 项；也可以先跳过。</p>`;
  if(step===3)fields=[['Serious relationship','认真建立关系','期待一个愿意长期一起成长的人'],['Open to connection','先认识彼此','相遇、交流，让关系自然发生'],['Already in love','已经有了彼此','把已经存在的爱连接起来'],['Just exploring','先探索一下','不急着承诺，先了解自己']].map(([value,label,desc])=>`<div class="radio-card"><input type="radio" id="intention-${value.replaceAll(' ','-')}" name="intention" value="${value}" ${draft.intention===value?'checked':''}><label for="intention-${value.replaceAll(' ','-')}">${label}<p>${desc}</p></label></div>`).join('')+`<blockquote class="identity-quote">“一起看世界，也在每一次选择里，认真看见彼此。”</blockquote>`;
  if(step===4)fields=`<label for="identity-statement">用自己的话，描述你期待的关系</label><textarea id="identity-statement" name="statement" maxlength="200" placeholder="我期待的爱，是……">${escape(draft.statement)}</textarea><p class="small muted">最多 200 个字；这是你的表达，不是链上承诺。</p><div class="check"><input id="identity-visible" type="checkbox" name="discoverable" ${draft.discoverable?'checked':''}><label for="identity-visible">允许已登录用户发现我的公开资料。昵称、城市、年龄、兴趣、意向与宣言会被看见；随时可关闭。</label></div>`;
  return `<section class="identity-page"><div class="id-progress"><span class="segs" aria-hidden="true">${[1,2,3,4].map(n=>`<span class="seg ${n<=step?'on':''}"></span>`).join('')}</span><span class="lbl">Step 0${step} of 04 · ${step}/4</span></div><span class="id-eyebrow">Identity &amp; Resonance</span>${head(titles[step-1],subs[step-1])}<form class="form id-form" data-form="identity-step">${fields}<div class="id-next"><div class="id-go">${submit(step===4?(state.preview?'完成预览草稿':'保存我的身份'):'继续')}</div><small>Next: ${['Your Interests','Your Intention','Your Words','Save'][step-1]}</small></div>${step>1?btn('上一步','identity-back','type="button"','light'):btn('返回','home','type="button"','light')}</form></section>`;
}
