export const emptyProfile=()=>({name:'',city:'',gender:'',age:'',interests:[],statement:'',intention:'Serious relationship',discoverable:false,avatarUrl:'',occupation:''});
export const carryIdentityDraft=(existingProfile,visitorDraft)=>!existingProfile&&visitorDraft?{...visitorDraft,interests:[...(visitorDraft.interests||[])]}:null;
export const interestChoices=[['Music','音乐','in-music.webp'],['Travel','旅行','in-travel.webp'],['Photography','摄影','in-photo.webp'],['Food','美食','in-food.webp'],['Reading','阅读','in-reading.webp'],['Movies','电影','in-movies.webp'],['AI','AI','in-ai.webp'],['Art','艺术','in-art.webp'],['Sports','运动','in-sports.webp']];
export function updateIdentity(draft,step,fields){
  const next={...emptyProfile(),...draft,interests:[...(draft?.interests||[])]};
  if(step===1){for(const key of ['name','city','gender','age','avatarUrl','occupation'])next[key]=String(fields[key]||'').trim();if(!next.name)throw new Error('先告诉我们你的昵称。');if(next.name.length>40)throw new Error('昵称最多 40 个字。');if(next.avatarUrl){let ok=false;try{const u=new URL(next.avatarUrl);ok=u.protocol==='https:'&&!u.username&&!u.password;}catch{}if(!ok)throw new Error('头像链接必须是 HTTPS 图片地址（HTTPS only）。');}if(next.occupation.length>80)throw new Error('职业最多 80 个字。');}
  if(step===3)next.intention=String(fields.intention||next.intention).trim();
  if(step===4){next.statement=String(fields.statement||'').trim();next.discoverable=Boolean(fields.discoverable);if(next.statement.length>200)throw new Error('爱情宣言最多 200 个字。');}
  if(next.interests.length>8)throw new Error('最多选择八项兴趣。');return next;
}
export function onboardingView(state,{escape,head,submit,btn,avatar}){
  const step=state.identityStep||1,draft={...emptyProfile(),...state.profile,...state.identityDraft};
  const titles=['Tell us about you','What do you love?','What are you looking for?','Love, in your own words'];
  const field=(label,name,value,attrs='')=>`<div class="input-row"><label for="identity-${name}">${label}</label><input id="identity-${name}" name="${name}" value="${escape(value)}" ${attrs}></div>`;
  let fields='';
  if(step===1)fields=`<div class="identity-portrait">${avatar?avatar(draft.name||'你','你的身份首字'): `<span class="identity-initial" aria-hidden="true">${escape(Array.from(draft.name)[0]||'你')}</span>`}<span class="small muted">你的故事，从你开始</span></div><div class="identity-fields">${field('昵称','name',draft.name,'required maxlength="40" autocomplete="nickname" placeholder="你希望被怎样称呼"')}${field('头像链接（HTTPS）','avatarUrl',draft.avatarUrl,'maxlength="300" inputmode="url" placeholder="https://… 一张你喜欢的照片链接"')}${field('职业 · 可选','occupation',draft.occupation,'maxlength="80" placeholder="你在做什么"')}${field('性别 · 可选','gender',draft.gender,'maxlength="30" placeholder="由你定义"')}${field('城市','city',draft.city,'maxlength="60" autocomplete="address-level2" placeholder="你生活的地方"')}${field('年龄 · 可选','age',draft.age,'maxlength="30" placeholder="例如 20–26"')}</div>`;
  if(step===2)fields=`<div class="interest-grid">${interestChoices.map(([value,label,image])=>`<button type="button" class="interest ${draft.interests.includes(value)?'selected':''}" data-action="identity-interest" data-value="${value}" aria-pressed="${draft.interests.includes(value)}"><img src="/assets/${image}" width="160" height="108" alt=""><span>${label}<small>${value}</small></span></button>`).join('')}</div><p class="small muted center">已选择 ${draft.interests.length}/8 项；也可以先跳过。</p>`;
  if(step===3)fields=[['Serious relationship','认真建立关系','期待一个愿意长期一起成长的人'],['Open to connection','先认识彼此','相遇、交流，让关系自然发生'],['Already in love','已经有了彼此','把已经存在的爱连接起来'],['Just exploring','先探索一下','不急着承诺，先了解自己']].map(([value,label,desc])=>`<div class="radio-card"><input type="radio" id="intention-${value.replaceAll(' ','-')}" name="intention" value="${value}" ${draft.intention===value?'checked':''}><label for="intention-${value.replaceAll(' ','-')}">${label}<p>${desc}</p></label></div>`).join('')+`<blockquote class="identity-quote">“一起看世界，也在每一次选择里，认真看见彼此。”</blockquote>`;
  if(step===4)fields=`<label for="identity-statement">用自己的话，描述你期待的关系</label><textarea id="identity-statement" name="statement" maxlength="200" placeholder="我期待的爱，是……">${escape(draft.statement)}</textarea><p class="small muted">最多 200 个字；这是你的表达，不是链上承诺。</p><div class="check"><input id="identity-visible" type="checkbox" name="discoverable" ${draft.discoverable?'checked':''}><label for="identity-visible">允许已登录用户发现我的公开资料。昵称、城市、年龄、兴趣、意向与宣言会被看见；随时可关闭。</label></div>`;
  return `<section class="identity-page"><div class="journey-stepper" aria-label="创建身份，第 ${step} 步，共四步">${[1,2,3,4].map(n=>`<span class="${n<=step?'done':''}"></span>`).join('')}<b>${step}/4</b></div>${head(titles[step-1],['从一个属于你的名字开始。','选择几件让你心动的事。','每一种开始，都值得认真对待。','不用完美，真诚就很好。'][step-1])}<form class="form" data-form="identity-step">${fields}${submit(step===4?(state.preview?'完成预览草稿':'保存我的身份'):'继续')}${step>1?btn('上一步','identity-back','type="button"','light'):btn('返回','home','type="button"','light')}</form></section>`;
}
