export function settingsView(state,h){
  const {escape:e,short,btn,head,ring,notice,icon,avatar,settingRow}=h;
  const guest=state.preview||state.previewOnly,r=state.relation,back=route=>`<div class="bell-back">${btn(icon('back')+' 返回','journey-back',`data-route="${route}"`,'light compact')}</div>`;
  if(state.route==='me'){
    const active=r?.status==='ACTIVE',days=active?Math.max(1,Math.floor((Date.now()/1000-r.createdAt)/86400)+1):null;
    const peer=state.chainAddress&&r?.a?(r.a.toLowerCase()===state.chainAddress.toLowerCase()?r.b:r.a):null;
    const memoryCount=(state.memories||[]).filter(m=>m.type!=='vow').length;
    const proofCount=(state.proofs||[]).length;
    const metric=(value,label,icon2,action,special)=>`<button data-action="${action}" class="bell-metric ${special?'rose':''}"><strong>${e(value)}</strong><span>${icon2} ${e(label)}</span></button>`;
    const group=(label,badge,rows)=>`<section class="bell-me-group"><div class="bell-me-label"><span>${e(label)}</span>${badge||''}</div><div class="bell-settings-group">${rows}</div></section>`;
    const meRow=(iconName,title,action2,attrs='',badge='',desc='',right='')=>`<button class="bell-me-row" data-action="${action2}" ${attrs}><span class="bell-me-row-icon">${icon(iconName)}</span><span class="bell-me-row-body"><span class="bell-me-row-top"><b>${e(title)}</b>${badge}</span><small>${e(desc)}</small></span>${right||icon('next')}</button>`;
    const pill=(text,cls='blush')=>`<span class="bell-me-pill ${cls}">${e(text)}</span>`;
    const latestProof=guest?null:(state.proofs||[])[0]||null;
    const portrait=state.profile?.avatarUrl&&/^(https:\/\/|\/assets\/)/.test(state.profile.avatarUrl)?`<span class="bell-me-photo"><img class="bell-face" src="${e(state.profile.avatarUrl)}" alt="${e(state.profile?.name||'我的头像')}" referrerpolicy="no-referrer"></span>`:`<span class="bell-me-photo">${avatar(state.profile?.name||'你')}</span>`;
    return `<div class="bell-me-hero"><div class="bell-me-avatars"><i class="bell-me-glow"></i>${portrait}${peer?`<span class="bell-me-partner">${avatar(short(peer))}<b>✦</b></span>`:''}${days!==null?`<em>${icon('heart')} Day ${days}</em>`:''}</div><h1>${e(state.profile?.name||'Your Space')}</h1><p>${state.profile?.occupation?e(state.profile.occupation)+' · ':''}${guest?'访客浏览 · 未登录':active?`${e(short(state.user))} · Ring #${e(r.id)} 已建立`:e(short(state.user))}</p><div class="bell-me-metrics">${metric(guest?'—':memoryCount,'Memories',icon('image'),'story')}${metric(guest||!r?'—':r.vowCount??'—','Vows Sealed',icon('shield'),'vows',true)}${metric(guest?'—':state.balance||'0','BOT Bond',icon('wallet'),'bond')}</div></div>`
    +group('Shared Trust & Ledger',`<span class="bell-me-badge ok">${icon('shield')}${state.config?.chainConfigured?'BOT Chain':'链未配置'}</span>`,meRow('wallet',state.authProvider==='privy'?'Smart Account':'EOA 钱包','copy-address',`data-copy="${e(state.chainAddress||state.user||'')}"`,pill(state.authProvider==='privy'?'AA 托管':'本人签名','ok'),short(state.chainAddress||state.user),icon('copy'))+meRow('shield','View On-chain Proofs',latestProof?'proof-detail':'proofs',latestProof?`data-hash="${e(latestProof.hash)}"`:'',latestProof?pill('View Sheet','blush'):'',latestProof?`${e((latestProof.actions||[]).join(' · ')||'已验证回执')} · 区块 ${e(latestProof.block??'—')}`:'完成真实操作后出现在这里'))
    +group('Shared Space · 共同空间','',meRow('lock','Bell Vault & 加密记忆','vault','',pill('AES-GCM','ok'),'客户端加密 · 仅你们可读')+meRow('heart','Echo Connections','echo-chat','data-inbox="true"','','查看与回应连接请求')+meRow('gift','Love Witness','witness','',pill('设计偏好','blush'),'为共同故事设计一份见证'))
    +group('Relationship Governance','',meRow('user','About You · 身份资料','identity','','','昵称、兴趣与关系意向')+meRow('shield','Privacy & Security','privacy','','','由你决定公开范围')+meRow('ring','Relationship Settings','relationship-settings','','','共同选择与关系记录')+meRow('book','Export Romantic Archive','export','','','导出加密档案（不含私钥）',icon('copy'))+meRow('bell','Help & Support','help','','','了解如何开始'))
    +(!guest&&active?`<section class="bell-me-danger"><div class="row between"><div><b>${icon('heart_broken')||'♡'} End Consensus & Covenant</b><small>归档誓言至永久加密冷存储</small></div>${btn('Initiate','request-end','','danger compact')}</div><p class="small">${icon('clock')}结束需要双方共同确认，或等待链上 7 天期限；不允许单方面销毁。</p></section>`:'')
    +(guest?`<div class="bell-settings-group">${settingRow('查看完整使用路径','journey-index','next','浏览所有页面与状态')}${settingRow('连接钱包，开启我的空间','login','','登录后同步你的真实账户')}</div>`:`<div class="bell-settings-group">${settingRow('退出账户','logout','logout','安全退出当前会话')}</div>`)
    +`<footer class="bell-me-signoff"><span class="line"></span><em>Consensus in Love</em><span class="line"></span><small>Secured by BOT Chain · Encrypted Memories · 0 mock</small></footer>`;
  }
  if(state.route==='relationship-settings')return back('me')+head('Relationship Settings','尊重彼此的选择，也珍惜共同留下的历史。')+`<div class="bell-settings-group">${settingRow('View On-chain Proofs','proofs','shield','查看经过验证的真实交易')}${settingRow('Manage Our Ring','home','ring',r?.id&&r.id!=='0'?'Ring #'+r.id:'尚未建立活动 Ring')}${settingRow('Data & Privacy','privacy','lock','公开资料与加密记忆')}${settingRow('Our Past Rings','history','book','回看已确认的关系记录')}</div>`+endingActions(state,h);
  if(state.route==='archived'||state.route==='home'&&r?.status==='ARCHIVED')return `<div class="bell-archive">${head('Archived','A chapter we will always value.')}${ring('ARCHIVED')}<p>${r?.a?e(short(r.a))+' × '+e(short(r.b)):'还没有加载已归档的关系'}</p><p class="quote">共同的历史，值得被温柔保留。</p>${btn('View Our History','story','','rose')}${r?.status==='ARCHIVED'?`<div class="actions">${btn('取回我的剩余贡献','withdraw','','light')}</div>`:notice('页面布局预览，不代表存在一份已归档的关系。')}</div>`;
  if(state.route==='waiting'||state.route==='acceptance'||state.route==='home'&&['WAITING','INVITED'].includes(r?.status)){
    const incoming=r?.status==='INVITED',loaded=['WAITING','INVITED'].includes(r?.status),expired=loaded&&r.expires*1000<Date.now();
    return back('path')+head(incoming?'A shared chapter begins with you.':'Invitation Sent',incoming?'只有你自己的选择，才能完成这枚 Ring。':'等待另一位参与者的回应。')+ring('INVITED')+`<div class="bell-invite-facts"><p>${icon('ring')}A unique relationship for two</p><p>${icon('shield')}Recorded on BOT Chain</p><p>${icon('heart')}A shared Ring SBT</p></div>`+(loaded?notice(`${incoming?'来自':'发给'} ${e(short(r.inviter||r.invitee))} · ${expired?'邀请已过期':'到期时间 '+e(new Date(r.expires*1000).toLocaleString('zh-CN'))}`):notice('布局预览：尚未加载真实邀请，不能签名接受。'))+`<div class="actions">${loaded?(incoming&&!expired?btn('Accept & Sign','accept','','rose')+btn('Decline','decline-invite','','light'):incoming?btn('释放过期邀请','decline-invite','','light'):btn('Cancel Invitation','cancel-invite','','light')):btn('查看接收与签名说明','invitation-preview','','light')}${!guest?btn('刷新邀请状态','refresh','','light'):''}</div>`;
  }
  if(state.route==='proofs')return back('relationship-settings')+head('Our On-chain Proofs','共同确认的每一步，都有可核对的记录。')+(state.proofs||[]).map(p=>`<article class="card"><div class="row"><h3>${e(p.actions.join(' · '))}</h3><span class="pill ok">${icon('shield')}Confirmed</span></div><p class="small muted bell-hash">${e(short(p.hash))}</p>${btn('查看证明','proof-detail',`data-hash="${e(p.hash)}"`,'light')}</article>`).join('')+(!(state.proofs?.length)?`<div class="bell-empty-art">${icon('shield')}<h2>等待第一份共同证明</h2><p>完成真实钱包操作并收到成功回执后，记录会显示在这里。</p>${btn(guest?'连接钱包':'查看我们的 Ring',guest?'login':'home','','rose')}</div>`:'');
  return undefined;
}
function endingActions(state,{btn,notice,escape:e}){
  const r=state.relation;if(!r||state.preview||state.previewOnly)return notice('建立真实 Ring 后，可以在这里管理结束与归档。');
  if(r.status==='ACTIVE')return `<div class="actions">${btn('End Relationship','request-end','','danger')}</div>`;
  if(r.status==='ENDING')return notice('等待另一方共同确认，或等待链上七天期限。')+(r.requester?.toLowerCase()!==(state.chainAddress||state.user)?.toLowerCase()?btn('Confirm End','confirm-end','','danger'):'')+(Date.now()/1000>=r.endingAt?btn('Finalize End','finalize-end','','danger'):'');
  return notice(e(r.status==='ARCHIVED'?'这枚 Ring 已归档，共同记录仍可回看。':'当前没有活动 Ring。'));
}
