import {text as e,icon,avatar} from './components.js';
const action=(label,name,attrs='',cls='')=>`<button class="btn ${cls}" data-action="${name}" ${attrs}>${label}</button>`;
const heading=(title,sub)=>`<header class="head"><h1>${title}</h1><p>${sub}</p></header>`;
export function communityView(state){
  const candidate=state.candidates.find(c=>c.address===state.echoAddress),preview=state.preview||state.previewOnly;
  const back=action(icon('back')+' 共鸣雷达','discover','','light compact');
  if(state.route==='echo-results')return back+heading('People who might resonate','不急着选择，先了解彼此。')+(state.candidates.length?`<div class="bell-echo-grid">${state.candidates.map(c=>`<article class="bell-echo-card"><button class="bell-portrait" data-action="echo-detail" data-address="${e(c.address)}" aria-label="查看 ${e(c.name)}">${avatar(c.name)}</button><h2>${e(c.name)}${c.age?', '+e(c.age):''}</h2><p class="small muted">${e(c.city||'城市未填写')}</p><div class="chips">${c.interests.map(i=>`<span class="pill">${e(i)}</span>`).join('')}</div><p>${e(c.statement||'让第一次对话，成为了解的开始。')}</p><div class="row">${action(icon('heart'),'radar-save',`data-address="${e(c.address)}" aria-label="${c.saved?'取消收藏':'收藏'}"`,'light compact')}${action('了解彼此','echo-detail',`data-address="${e(c.address)}"`,'rose compact')}</div></article>`).join('')}</div>`:`<div class="bell-empty-art">${icon('bell')}<h2>等待一份真实的共鸣</h2><p>登录并完善资料后，开始寻找与你兴趣相近的人。</p>${action(preview?'连接钱包':'重新探测',preview?'login':'discover')}</div>`);
  if(state.route==='echo-detail')return back+(!candidate?heading('Possible Echo','先在共鸣雷达选择一位真实候选人。')+action('查看推荐结果','echo-results'): `<div class="bell-profile-hero">${avatar(candidate.name)}<h1>${e(candidate.name)}${candidate.age?', '+e(candidate.age):''}</h1><p>${icon('pin')}${e(candidate.city||'城市未填写')}</p></div><div class="chips">${candidate.interests.map(i=>`<span class="pill">${e(i)}</span>`).join('')}</div><p class="bell-introduction">${e(candidate.statement||'对方还没有填写自我介绍。')}</p><section class="bell-reasons"><h3>Why you resonated</h3>${candidate.reasons.map(reason=>`<p>${icon('ring')}${e(reason)}</p>`).join('')}<small class="muted">根据对方主动公开的资料推荐，匹配不代表关系成立。</small></section><div class="actions">${action("Let's Connect",'echo-connect',`data-address="${e(candidate.address)}"`,'rose')}${action('查看连接状态','echo-chat',`data-address="${e(candidate.address)}"`,'light')}</div>`);
  if(state.route==='echo-chat'&&!state.echoAddress&&state.connections?.length)return back+heading('Echo Connections','每一份回应，都由你自己决定。')+state.connections.map(connection=>{const incoming=connection.recipient.toLowerCase()===state.user?.toLowerCase(),peer=incoming?connection.requester:connection.recipient;return `<article class="card"><div class="row">${avatar(peer)}<div><h3>${e(peer.slice(0,6)+'…'+peer.slice(-4))}</h3><p class="small muted">${e({pending:'等待回应',accepted:'已同意连接',declined:'已拒绝',blocked:'已屏蔽'}[connection.status]||connection.status)}</p></div></div><div class="actions">${incoming&&connection.status==='pending'?action('接受连接','connection-respond',`data-id="${e(connection.id)}" data-decision="accept"`,'rose')+action('暂不连接','connection-respond',`data-id="${e(connection.id)}" data-decision="decline"`,'light'):''}${action('查看连接空间','echo-chat',`data-address="${e(peer)}"`,'light')}</div></article>`;}).join('');
  if(state.route==='echo-chat')return chatView(state,candidate,back);
  return undefined;
}
function chatView(state,candidate,back){
  const connection=(state.connections||[]).find(c=>[c.requester,c.recipient].some(a=>a.toLowerCase()===state.echoAddress?.toLowerCase()));
  const incoming=connection?.status==='pending'&&connection.recipient.toLowerCase()===state.user?.toLowerCase();
  const status={pending:'等待回应',accepted:'已同意连接',declined:'已拒绝',blocked:'连接已屏蔽'};
  const response=incoming?`<div class="actions">${action('接受连接','connection-respond',`data-id="${e(connection.id)}" data-decision="accept"`,'rose')}${action('暂不连接','connection-respond',`data-id="${e(connection.id)}" data-decision="decline"`,'light')}</div>`:!connection&&candidate?action('发送连接请求','echo-connect',`data-address="${e(candidate.address)}"`,'rose'):'';
  return back+`<div class="bell-chat-header">${avatar(candidate?.name||state.echoAddress)}<div><h2>${e(candidate?.name||'Echo Chat')}</h2><small>${connection?e(status[connection.status]||connection.status):'尚未建立连接'}</small></div></div><div class="bell-conversation"><span class="pill">这是你们开始了解的地方</span><div class="bell-empty-art">${icon('heart')}<h3>先从一次双向的同意开始</h3><p>${connection?.status==='accepted'?'连接已由对方接受。聊天传送服务尚未接入；以下文字只保存在本页草稿。':'连接请求会发送给真实账户，对方可以接受或拒绝。'}</p>${response}</div>${state.chatDraft?`<div class="bell-chat-bubble"><p>${e(state.chatDraft)}</p><small>未发送 · 本页草稿</small></div>`:''}</div><form class="bell-composer" data-form="chat-draft"><label class="sr-only" for="chat-message">聊天草稿</label><input id="chat-message" name="message" maxlength="2000" placeholder="写一句想说的话…" value="${e(state.chatDraft||'')}"><button class="icon" type="submit" aria-label="保留本页草稿">${icon('send')}</button></form><p class="small muted">聊天草稿不会上传，也不会显示假回复。</p>`;
}
