import {onboardingView} from './onboarding.js';
const isMedia=memory=>['note','photo','video'].includes(memory.type);
export const storyItems=(memories,filter='all')=>memories.filter(isMedia).filter(m=>filter==='all'||m.type===filter);
export const mediaCounts=memories=>({photo:memories.filter(m=>m.type==='photo').length,video:memories.filter(m=>m.type==='video').length,note:memories.filter(m=>m.type==='note').length,vow:memories.filter(m=>m.type==='vow').length,goal:memories.filter(m=>m.type==='goal').length});
export const products=[['digital','Digital Ring','数字见证','ring-hero.jpg','把真实的共同经历，变成一枚专属纪念。'],['physical','Physical Ring','实体戒指','ring-box.jpg','保留设计偏好，等待真正的制作与履约接入。'],['object','Memory Object','记忆物件','keepsake.jpg','让一段故事，有一个可以触摸的载体。']];
export const goalCategories={travel:['一起旅行','japan-trip.jpg'],anniversary:['纪念日','anniversary.jpg'],home:['未来之家','future-home.jpg']};
export function journeyView(state,h){
  const {escape:e,short,head,btn,ring,notice,input,submit}=h;
  const guest=state.preview||state.previewOnly,r=state.relation,active=r?.status==='ACTIVE',archived=r?.status==='ARCHIVED';
  const memories=guest?(state.previewMemories||[]):state.memories||[],counts=mediaCounts(memories);
  const back=(route='home')=>btn('返回','journey-back',`data-route="${route}"`,'light compact');
  const blank=(title,description,action,label)=>`<div class="blank"><h2>${title}</h2><p>${description}</p>${action?btn(label,action):''}</div>`;
  const privateHint=guest?'访客浏览不加载真实账户记录；填写内容只是当前页面的未上传草稿。':r?.id&&r.id!=='0'?'只属于当前 Ring 的共同空间。':'现在是你的私人空间，建立 Ring 后再开始记录共同内容。';
  if(state.route==='identity')return onboardingView(state,h);
  if(state.route==='path'||(state.route==='home'&&(!r||r.status==='NONE'))){
    return head('Choose your path','你可以先寻找共鸣，也可以连接已经选择的彼此。')+`<div class="journey-grid">${[['discover','Find Someone','还没有合适的人','find-someone.jpg'],['invite-page','Bind My Person','我们已经找到了彼此','bind-person.jpg']].map(([action,title,desc,image])=>`<button class="path-card" data-action="${action}"><img src="/assets/${image}" width="360" height="240" alt=""><h2>${title}</h2><p>${desc}</p></button>`).join('')}</div><div class="actions">${btn(state.profile?'修改身份资料':'从四步创建身份开始','identity','','light')}${guest?btn('查看完整使用路径','journey-index','','light'):''}</div>`+(!guest&&state.error?notice(e(state.error)):'');
  }
  if(state.route==='journey-index')return head('从认识，到共同生活','每一步都可以回看，不会在预览中替你签署承诺。')+`<div class="journey-index">${[['identity','01 · 四步身份创建'],['path','02 · 寻找或绑定彼此'],['discover','03 · 共鸣雷达'],['invite-page','04 · 发送邀请'],['invitation-preview','05 · 接收与签名说明'],['ceremony','06 · 戒指仪式'],['story','07 · 我们的故事'],['vows','08 · 我们的誓言'],['bond','09 · 共同目标'],['vault','10 · 加密记忆仓库'],['witness','11 · 爱的见证'],['privacy','12 · 隐私与设置']].map(([action,label])=>btn(label,action,'','light')).join('')}</div>`;
  if(state.route==='invite-page')return back('path')+head('Send a Ring Invitation','给已经选择的那个人，一次共同确认的邀请。')+ring('INVITED')+`<form class="form" data-form="invite">${input('对方的钱包地址','address',state.inviteAddress||'','required pattern="0x[0-9a-fA-F]{40}" placeholder="0x…"')}${notice('先核对地址，再由你的钱包创建链上邀请。对方仍需独立接受；此步骤不是资金转账。')}${submit(guest?'查看邀请前核对':'使用钱包创建邀请')}</form>`;
  if(state.route==='invitation-preview')return back('path')+head('Only you can complete this Ring','接受与拒绝，始终由你自己决定。')+ring('INVITED')+`<div class="card"><h2>一次双向的选择</h2><p>正式邀请会显示真实邀请人的钱包、到期时间与链上状态。目前没有加载一份真实邀请。</p><ul><li>创建一份活动关系</li><li>不会在接受时转移资金</li><li>钱包签名前可以退出或拒绝</li></ul></div>`+btn('查看戒指仪式页面','ceremony')+notice('页面预览，不代表已收到或接受邀请。');
  if(state.route==='ceremony')return `<div class="journey-ceremony">${head(active?'Our Ring':'Our Ring · 仪式预览',active?'两次选择，成为一段共同的历史。':'尚未建立链上关系。这里展示仪式布局，不代表签名成功。')}${ring(active?'ACTIVE':'NONE')}${active?`<p>${e(short(r.a))} × ${e(short(r.b))}</p><p class="small muted">Born ${e(new Date(r.createdAt*1000).toLocaleDateString())} · Ring #${e(r.id)}</p>`:''}<p class="quote">Forever does not begin with a promise.<br>It begins with two people choosing the same thing.</p>${btn(active?'Enter Our Ring':'继续浏览我们的故事',active?'home':'story')}</div>`;
  if(state.route==='home'&&active){const days=Math.max(1,Math.floor((Date.now()/1000-r.createdAt)/86400)+1);return head('Our Ring',`${e(short(r.a))} × ${e(short(r.b))}`)+`<div class="center"><p class="number">${days}</p><p class="small muted">Days Together</p></div>`+ring('ACTIVE')+`<div class="stats"><button data-action="story"><strong>${counts.photo+counts.video+counts.note}</strong><span>Memories</span></button><button data-action="vows"><strong>${r.vowCount}</strong><span>Confirmed Vows</span></button><button data-action="bond"><strong>${e(state.balance)}</strong><span>BOT Bond</span></button></div><div class="card"><h3>Today · 今天也值得记住</h3><p>${memories.find(isMedia)?.content?.title?e(memories.find(isMedia).content.title):'从一张照片或一句话开始你们的故事。'}</p>${btn('记录今天','memory')}</div><div class="actions">${btn('把爱变成见证','witness','','light')}${btn('查看真实链上证明','proofs','','light')}</div>`;}
  if(state.route==='story'){
    const filter=state.storyFilter||'all',items=storyItems(memories,filter),groups=new Map();for(const m of items){const month=new Date(m.at).toLocaleDateString('zh-CN',{year:'numeric',month:'long'});if(!groups.has(month))groups.set(month,[]);groups.get(month).push(m);}
    return head('Our Story','All the moments, big or small.')+`<div class="row">${btn('+ 添加记忆','memory','','compact')}${btn('记忆仓库','vault','','light compact')}</div><div class="journey-filters" aria-label="记忆分类">${[['all','全部'],['photo','照片'],['video','视频'],['note','文字']].map(([value,label])=>`<button class="chip ${filter===value?'active':''}" data-action="story-filter" data-value="${value}" aria-pressed="${filter===value}">${label}</button>`).join('')}</div>`+notice(privateHint)+[...groups].map(([month,items])=>`<section class="story-month"><h2>${e(month)}</h2><div class="timeline">${items.map(m=>`<article class="event"><p class="small muted">${e(new Date(m.at).toLocaleDateString())} · ${guest?'未上传草稿':e(short(m.owner))}</p><button class="title" data-action="memory-detail" data-id="${e(m.id)}">${e(m.content?.title||'加密记忆')}</button><p>${e(m.content?.text?.slice(0,180)||m.error||'')}</p>${/^data:image\/(jpeg|png|webp);base64,/.test(m.content?.image||'')?`<img class="photo" src="${e(m.content.image)}" width="320" height="220" alt="${e(m.content?.title||'记忆照片')}">`:m.type==='video'?'<span class="pill">视频 · 点击详情播放</span>':''}</article>`).join('')}</div></section>`).join('')+(!items.length?blank('还没有这类记忆','保留一个真实的片刻，而不是填入示例故事。','memory','记下第一个片刻'):'');
  }
  if(state.route==='vows')return head('Our Vows','A thought becomes a Vow only when both of you choose it.')+`<div class="row"><span class="pill">${guest?'未加载':r?.vowCount??'—'} · 已确认誓言</span>${btn('+ New Vow','new-vow','','compact')}</div>`+(r?.vows||[]).map(v=>{const m=memories.find(m=>m.body?.hash?.toLowerCase()===v.hash.toLowerCase());return `<button class="list-row card" data-action="vow-detail" data-index="${v.index}"><div><h3>${e(m?.content?.text||v.text||'加密正文暂不可读')}</h3><span class="pill ${v.confirmed?'ok':'pending'}">${v.confirmed?'双方已确认':'等待另一位参与者确认'}</span></div><span aria-hidden="true">›</span></button>`;}).join('')+(!(r?.vows?.length)?blank('把一个想法，变成共同选择','只有两人的真实确认，才会成为生效誓言。','new-vow','写下一句誓言'):'');
  if(state.route==='bond'){
    const goals=memories.filter(m=>m.type==='goal');return head('Our Bond','Give a future plan some weight.')+`<div class="row"><span class="pill">目标规划 · 链下加密</span>${btn('+ 新建目标','new-goal','','compact')}</div>`+goals.map(m=>{const goal=m.content,category=goalCategories[goal?.category]||goalCategories.travel;return `<article class="card plan-card"><img src="/assets/${category[1]}" width="360" height="160" alt=""><div><h2>${e(goal?.title||'加密目标')}</h2><p>${e(goal?.text||m.error||'')}</p><p class="small muted">目标预算 ${e(goal?.target||'未设置')} BOT · 不代表已存入</p>${(!archived&&(guest||m.owner?.toLowerCase()===state.user?.toLowerCase()))?btn('修改规划','edit-goal',`data-id="${e(m.id)}"`,'light'):''}</div></article>`;}).join('')+(!goals.length?`<div class="journey-grid">${Object.entries(goalCategories).map(([value,[label,image]])=>`<button class="plan-template" data-action="new-goal" data-category="${value}"><img src="/assets/${image}" width="320" height="160" alt=""><span>${label}</span><small>从你的真实计划开始</small></button>`).join('')}</div>`:'')+`<div class="card"><h2>你们的真实贡献</h2>${[r?.a,r?.b].filter(Boolean).map(address=>`<div class="proof-row"><span>${e(short(address))}</span><b>${e(state.formatAmount(r.balances?.[address]||'0'))} BOT</b></div>`).join('')||'<p class="muted">未加载活动 Ring 的链上余额。</p>'}<div class="actions">${active?btn('使用钱包存入 BOT','deposit'):archived?btn('取回我的剩余贡献','withdraw'):''}</div></div>`+notice('规划预算不是余额。现有合约尚无按目标分账功能；存入只记在出资钱包名下，不会显示假的目标进度。');
  }
  if(state.route==='vault')return back('me')+head('Bell Vault','We store memories privately, and proofs publicly.')+`<div class="card center"><h2>Our Memories</h2><p class="muted">${e(privateHint)}</p><div class="vault-grid">${[['photo','Photos'],['video','Videos'],['note','Notes'],['vow','Vows'],['goal','Plans']].map(([type,label])=>`<div><strong>${guest?'—':counts[type]}</strong><span>${label}</span></div>`).join('')}<div><strong>${guest?'预览':'AES-GCM'}</strong><span>Encrypted</span></div></div></div><div class="actions">${btn('Manage Memories','story')}${btn('Export Encrypted Archive','export','','light')}</div><details class="card"><summary>加密与备份说明</summary><p>记忆在本机使用 P-256 ECDH 与 AES-256-GCM 加密；服务器只保存密文。导出仅备份密文，不包含私钥。请保留首次登记的浏览器；跨设备密钥恢复和文档上传尚未接入。</p></details>`;
  if(state.route==='witness')return back()+head('Make It Real','Turn our Ring into something real.')+`<div class="journey-products">${products.map(([value,title,label,image,desc])=>`<button class="product-card" data-action="witness-detail" data-value="${value}"><img src="/assets/${image}" width="360" height="220" alt="${label}"><div><span class="eyebrow">${e(label)}</span><h2>${title}</h2><p>${desc}</p><span class="pill">查看设计 · 功能待接入</span></div></button>`).join('')}</div>`+notice('可以查看并选择设计偏好。当前没有可铸造的 Witness 合约或真实实体订单服务，不会收款或显示已铸造。');
  if(state.route==='witness-detail'){
    const product=products.find(p=>p[0]===state.witnessKind)||products[0],material=state.material||'Rose Gold';return back('witness')+head(product[1],product[2])+`<div class="ring-hero" data-material="${e(material)}"><img src="/assets/${product[3]}" width="280" height="280" alt="${e(product[2])}设计"></div><div class="card"><h2>Your Unique Ring</h2><p class="small muted">外观预览，不是已铸造或可购买的资产。</p><div class="proof-row"><span>Ring</span><b>${r?.id&&r.id!=='0'?'#'+e(r.id):'尚未建立'}</b></div><div class="proof-row"><span>Memories</span><b>${guest?'未加载':counts.photo+counts.video+counts.note}</b></div><div class="proof-row"><span>Confirmed Vows</span><b>${guest?'未加载':r?.vowCount??'尚未读取'}</b></div></div><h3>Material · 材质偏好</h3><div class="materials">${['Rose Gold','Silver','White Gold','Black Titanium'].map(value=>`<button class="material ${material===value?'active':''}" data-action="witness-material" data-value="${value}" aria-label="${value}" aria-pressed="${material===value}"></button>`).join('')}</div><p>${e(material)} · 仅当前页设计偏好</p><div class="actions">${btn(product[0]==='digital'?'查看铸造接入要求':'查看制作接入要求','witness-requirements')}</div>`;
  }
  if(state.route==='privacy')return back('me')+head('Privacy','由你决定，哪些内容可以被看见。')+`<form class="form" data-form="privacy"><div class="card"><h2>出现在共鸣雷达中</h2><div class="check"><input id="privacy-visible" type="checkbox" name="discoverable" ${state.profile?.discoverable?'checked':''}><label for="privacy-visible">允许登录用户发现公开资料</label></div><p class="small muted">公开范围为昵称、城市、年龄、兴趣、意向和宣言。私人记忆、加密目标和精确位置不会因此公开。</p></div>${submit(guest?'查看隐私设置':'保存隐私设置')}</form><div class="actions">${btn('撤回附近位置','radar-revoke-location','','light')}${btn('管理加密记忆','vault','','light')}</div>`;
  return undefined;
}
