export function settingsView(state,h){
  const {escape:e,short,btn,head,ring,notice,icon,avatar,settingRow}=h;
  const guest=state.preview||state.previewOnly,r=state.relation,back=route=>`<div class="bell-back">${btn(icon('back')+' 返回','journey-back',`data-route="${route}"`,'light compact')}</div>`;
  if(state.route==='me')return `<div class="bell-me">${avatar(state.profile?.name||'你')}<div><h1>${e(state.profile?.name||'Your Space')}</h1><p>${guest?'访客浏览 · 未登录':e(short(state.user))}</p></div></div><div class="bell-settings-group">${settingRow('Wallet & Smart Account','wallet-info','wallet',guest?'连接后拥有你的专属账户':short(state.chainAddress||state.user))}${settingRow('Echo Connections','echo-chat','heart','查看与回应连接请求','data-inbox="true"')}${settingRow('About You','identity','user','身份、兴趣与关系意向')}${settingRow('Privacy & Security','privacy','shield','由你决定公开范围')}${settingRow('Bell Vault','vault','lock','Encrypted for both of you.')}${settingRow('Relationship Settings','relationship-settings','ring','共同选择与关系记录')}${settingRow('Love Witness','witness','gift','为共同故事设计一份见证')}${settingRow('Help & Support','help','book','了解如何开始')}${guest?settingRow('查看完整使用路径','journey-index','next','浏览所有页面与状态'):settingRow('退出账户','logout','logout','安全退出当前会话')}</div>`;
  if(state.route==='relationship-settings')return back('me')+head('Relationship Settings','尊重彼此的选择，也珍惜共同留下的历史。')+`<div class="bell-settings-group">${settingRow('View On-chain Proofs','proofs','shield','查看经过验证的真实交易')}${settingRow('Manage Our Ring','home','ring',r?.id&&r.id!=='0'?'Ring #'+r.id:'尚未建立活动 Ring')}${settingRow('Data & Privacy','privacy','lock','公开资料与加密记忆')}${settingRow('Our Past Rings','history','book','回看已确认的关系记录')}</div>`+endingActions(state,h);
  if(state.route==='archived'||state.route==='home'&&r?.status==='ARCHIVED')return `<div class="bell-archive">${head('Archived','A chapter we will always value.')}${ring('ARCHIVED')}<p>${r?.a?e(short(r.a))+' × '+e(short(r.b)):'还没有加载已归档的关系'}</p><p class="quote">共同的历史，值得被温柔保留。</p>${btn('View Our History','story','','rose')}${r?.status==='ARCHIVED'?`<div class="actions">${btn('取回我的剩余贡献','withdraw','','light')}</div>`:notice('页面布局预览，不代表存在一份已归档的关系。')}</div>`;
  if(state.route==='waiting'||state.route==='acceptance'||state.route==='home'&&['WAITING','INVITED'].includes(r?.status)){
    const incoming=r?.status==='INVITED',loaded=['WAITING','INVITED'].includes(r?.status),expired=loaded&&r.expires*1000<Date.now();
    return back('path')+head(incoming?'A shared chapter begins with you.':'Invitation Sent',incoming?'只有你自己的选择，才能完成这枚 Ring。':'等待另一位参与者的回应。')+ring('INVITED')+`<div class="bell-invite-facts"><p>${icon('ring')}A unique relationship for two</p><p>${icon('shield')}Recorded on BOT Chain</p><p>${icon('heart')}A shared Ring SBT</p></div>`+(loaded?notice(`${incoming?'来自':'发给'} ${e(short(r.inviter||r.invitee))} · ${expired?'邀请已过期':'到期时间 '+e(new Date(r.expires*1000).toLocaleString('zh-CN'))}`):notice('布局预览：尚未加载真实邀请，不能签名接受。'))+`<div class="actions">${loaded?(incoming&&!expired?btn('Accept & Sign','accept','','rose')+btn('Decline','decline-invite','','light'):incoming?btn('释放过期邀请','decline-invite','','light'):btn('Cancel Invitation','cancel-invite','','light')):btn('查看接收与签名说明','invitation-preview','','light')}${!guest?btn('刷新邀请状态','refresh','','light'):''}</div>`;
  }
  if(state.route==='proofs')return back('relationship-settings')+head('Our On-chain Proofs','共同确认的每一步，都有可核对的记录。')+(state.proofs||[]).map(p=>`<article class="card"><div class="row"><h3>${e(p.actions.join(' · '))}</h3><span class="pill ok">${icon('shield')}Confirmed</span></div><p class="small muted bell-hash">${e(short(p.hash))}</p>${btn('查看证明','proof-detail',`data-hash="${e(p.hash)}"`,'light')}</article>`).join('')+(!(state.proofs?.length)?`<div class="bell-empty-art">${icon('shield')}<h2>等待第一份共同证明</h2><p>完成真实钱包操作并收到成功回执后，记录会显示在这里。</p>${btn(guest?'连接钱包':'查看我们的 Ring',guest?'login':'home','','rose')}</div>`:'');
  return undefined;
}
function endingActions(state,{btn,notice,escape:e}){
  const r=state.relation;if(!r||state.preview||state.previewOnly)return notice('建立真实 Ring 后，可以在这里管理结束与归档。');
  if(r.status==='ACTIVE')return `<div class="actions">${btn('End Relationship','request-end','','danger')}</div>`;
  if(r.status==='ENDING')return notice('等待另一方共同确认，或等待链上七天期限。')+(r.requester?.toLowerCase()!==(state.chainAddress||state.user)?.toLowerCase()?btn('Confirm End','confirm-end','','danger'):'')+(Date.now()/1000>=r.endingAt?btn('Finalize End','finalize-end','','danger'):'');
  return notice(e(r.status==='ARCHIVED'?'这枚 Ring 已归档，共同记录仍可回看。':'当前没有活动 Ring。'));
}
