import {radarView} from './radar.js';
import {journeyView} from './journey.js';
import {chainIdentity} from './aa-action.js';
export const escape = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const short = value => value?value.slice(0,6)+'…'+value.slice(-4):'';
export const btn = (label,action,attrs='',cls='') => `<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
export const head = (title,sub='') => `<div class="head"><h1>${title}</h1><p>${sub}</p></div>`;
export const input = (label,name,value='',attrs='') => `<label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" value="${escape(value)}" ${attrs}>`;
export const ring = status => `<div class="ring-hero ${status==='ARCHIVED'?'archived':status==='ENDING'?'ending':status==='INVITED'?'waiting':''}"><img src="/assets/ring-float.jpg" width="280" height="280" alt="关系戒指"></div>`;
export const notice = text => `<div class="notice">${text}</div>`;
export const submit = label => `<div class="actions"><button class="btn" type="submit">${label}</button></div>`;
const statusLabel = {UNAVAILABLE:'链上状态尚未读取',NONE:'未建立关系',INVITED:'收到邀请',WAITING:'等待对方签名',ACTIVE:'关系已建立',ENDING:'等待结束确认',ARCHIVED:'已归档'};
export function view(state) {
  if(state.preview)state={...state,user:null,profile:state.previewProfile||null,relation:null,memories:[],proofs:[],candidates:[],history:[],error:''};
  if(state.user||state.preview||state.previewOnly){
    const optimized=journeyView(state,{escape,short,btn,head,input,notice,submit,ring});
    if(optimized!==undefined)return (state.preview?notice('访客预览 · 不加载真实账号数据。你输入的内容仅作为当前页面未上传草稿。'):'')+optimized;
  }
  if(state.preview){
    const banner=notice('访客预览 · 尚未登录。这里不加载真实用户、私人记忆或链上账户数据。保存、匹配和邀请需要钱包认证。');
    if(state.route==='me')return banner+head('Me','先看看你的专属空间。')+`<div class="actions">${btn('查看完整使用路径','journey-index')}${btn('身份资料','identity','','light')}${btn('Privacy · 隐私设置','privacy','','light')}${btn('Bell Vault · 记忆仓库','vault','','light')}${btn('Proof History · 链上证明','proofs','','light')}${btn('Witness · 爱的见证','witness','','light')}${btn('历史 Ring','history','','light')}${btn('连接钱包，开启我的空间','login','','light')}</div>`;
    if(state.route==='home')return banner+head('Choose your path','现在可以先浏览，不必连接钱包。')+ring('NONE')+`<div class="actions">${btn('还没有合适的人 · 共鸣雷达','discover')}${btn('查看身份资料页面','identity','','light')}${btn('浏览爱的见证','witness','','light')}</div>`;
    const previewState={...state,preview:false,previewOnly:true,user:'VISITOR_VIEW_ONLY',profile:null,relation:{id:'0',status:'NONE'},memories:[],proofs:[],candidates:[],history:[],balance:'0',error:''};
    if(state.route==='discover')previewState.radarError='访客预览未加载候选人。登录后 O 才会根据你的资料进行真实匹配。';
    return banner+view(previewState);
  }
  const {user,profile,relation,route,memories,proofs,candidates,config,error}=state;
  if(!user)return `<div class="gateway"><p class="eyebrow">CONSENSUS BELL</p>${ring('NONE')}${head('Forever begins<br>with one mutual yes.','Two signatures. One ring. A shared history.')}<div class="actions">${btn('邮箱或钱包登录','login')}${btn('先逛逛 · 跳过钱包','preview','','light')}${notice('邮箱登录会创建真实嵌入式钱包，也可连接已有钱包。访客浏览不创建账号。')}</div></div>`;
  const top=`<div class="top"><span class="eyebrow">CONSENSUS BELL</span><span class="small muted">${state.previewOnly?'访客预览':escape(profile?.name||short(user))}</span></div>`;
  const banner=error?notice(escape(error)):'';
  const chainUser=chainIdentity(state),r=relation||{id:'0',status:'UNAVAILABLE'},peer=r.a?(r.a.toLowerCase()===chainUser.toLowerCase()?r.b:r.a):null;
  const scope=r.id!=='0'?r.id:'personal';
  if(route==='home'&&!relation)return top+head('Our Ring','链上状态尚未读取。')+banner+notice('资料和私人笔记可以真实保存；关系建立与资金操作需要配置已部署合约。')+`<div class="actions">${btn('Find Someone · 共鸣雷达','discover')}${btn('重新读取','refresh','','light')}${btn('修改我的身份','identity','','light')}</div>`;
  if(route==='home'&&['INVITED','WAITING'].includes(r.status))return top+head(r.status==='INVITED'?'A Ring Invitation':'Invitation Sent',statusLabel[r.status])+banner+ring('INVITED')+notice(`${r.status==='INVITED'?'来自':'发给'} ${escape(short(r.inviter||r.invitee))} · 链上到期时间 ${escape(new Date(r.expires*1000).toLocaleString())}`)+`<div class="actions">${r.status==='INVITED'?btn('接受并使用钱包签名','accept')+btn('Decline','decline-invite','','light'):btn('Cancel Invitation','cancel-invite','','light')}${btn('刷新链上状态','refresh','','light')}</div>`;
  switch(route) {
    case 'identity':return top+head('Who are you?','资料属于你，可随时修改。')+`<form class="form" data-form="profile">${input('昵称','name',profile?.name||'','required maxlength="40"')}${input('城市','city',profile?.city||'','maxlength="60"')}${input('性别（可不公开）','gender',profile?.gender||'','maxlength="30"')}${input('年龄范围','age',profile?.age||'','maxlength="30"')}${input('兴趣（逗号分隔，最多八项）','interests',profile?.interests?.join(', ')||'','maxlength="240"')}${input('关系意向','intention',profile?.intention||'Serious relationship','maxlength="60"')}<label for="f-statement">What does love mean to you?</label><textarea id="f-statement" name="statement" maxlength="200">${escape(profile?.statement||'')}</textarea><div class="check"><input id="f-discoverable" type="checkbox" name="discoverable" ${profile?.discoverable?'checked':''}><label for="f-discoverable">允许其他已登录用户在发现页看到这些公开资料</label></div>${submit('保存我的资料')}</form>`+banner;
    case 'home':return top+head('Our Ring',statusLabel[r.status])+banner+(r.status==='NONE'||r.status==='INVITED'?ring(r.status)+`<div class="actions">${r.status==='INVITED'?notice(`来自 ${escape(short(r.inviter))} 的真实链上邀请`)+btn('使用当前钱包接受','accept'):btn('Bind My Person','invite')}${btn('Find Someone','discover','','light')}${btn('查看历史 Ring','history','','light')}</div>`:`<p class="center muted">${escape(short(r.a))} × ${escape(short(r.b))}</p><div class="center"><p class="number">${Math.max(1,Math.floor((Date.now()/1000-r.createdAt)/86400)+1)}</p><p class="small muted">Days Together</p></div>${ring(r.status)}<div class="stats"><div><strong>${memories.filter(m=>m.type!=='vow').length}</strong><span>Memories</span></div><div><strong>${r.vowCount}</strong><span>Confirmed Vows</span></div><div><strong>${state.balance}</strong><span>BOT Bond</span></div></div><div class="actions">${btn('记录今天','memory')}${btn('查看双方的钱包记录','proofs','','light')}</div>`);
    case 'story':return top+head('Our Story','私人内容经客户端加密，服务器只保存密文。')+banner+`<div class="row">${btn('+ 添加记忆','memory','','compact')}${btn('刷新','refresh','','light compact')}</div>`+memories.filter(m=>m.type!=='vow').map(m=>`<article class="card"><p class="small muted">${escape(new Date(m.at).toLocaleString())} · ${escape(short(m.owner))}</p><h2>${escape(m.content?.title||'加密记忆')}</h2><p>${escape(m.content?.text||m.error||'')}</p>${/^data:image\/(jpeg|png|webp);base64,/.test(m.content?.image||'')?`<img class="photo" src="${escape(m.content.image)}" width="320" height="220" alt="${escape(m.content.title)}">`:''}${m.owner.toLowerCase()===user.toLowerCase()&&r.status!=='ARCHIVED'?`<div class="actions">${btn('编辑','edit-memory',`data-id="${escape(m.id)}"`,'light')}${btn('删除','delete-memory',`data-id="${escape(m.id)}"`,'light')}</div>`:''}</article>`).join('')+(!memories.filter(m=>m.type!=='vow').length?notice('还没有记忆。从今天的一句话开始。'):'');
    case 'vows':return top+head('Our Vows','只有另一位参与者的链上确认，才让誓言生效。')+banner+btn('+ New Vow','new-vow')+(r.vows||[]).map(v=>{const m=memories.find(m=>m.body.hash?.toLowerCase()===v.hash.toLowerCase());return `<article class="card"><p class="quote">${escape(m?.content?.text||v.text||'加密正文尚未同步；内容哈希：'+v.hash)}</p>${v.text?notice('该誓言由公开接口提交，其正文已公开上链。'):''}<p class="small muted">${escape(short(v.by))} · ${v.confirmed?'双方已确认':'等待对方确认'}</p>${!v.confirmed&&v.by.toLowerCase()!==chainUser.toLowerCase()?btn('Confirm','confirm-vow',`data-index="${v.index}"`):''}</article>`;}).join('');
    case 'bond':return top+head('Our Bond','每一份贡献都记在出资人的钱包名下。')+banner+`<div class="card">${[r.a,r.b].filter(Boolean).map(p=>`<div class="proof-row"><span>${escape(short(p))}${p.toLowerCase()===chainUser.toLowerCase()?' · 你':''}</span><b>${escape(state.formatAmount(r.balances?.[p]||'0'))} BOT</b></div>`).join('')}</div><div class="actions">${r.status==='ACTIVE'?btn('存入 BOT','deposit'):r.status==='ARCHIVED'?btn('取回我的剩余贡献','withdraw'):notice('先建立 Active Ring，才可以存入。')}</div>`+notice('金额来自合约。当前合约尚未提供按目标分账和双方共同支出，不会用本地数字替代。');
    case 'discover':return radarView(state);
    case 'proofs':return top+head('Proof History','来自真实交易回执，不生成区块或交易哈希。')+proofs.map(p=>`<article class="card"><h3>${escape(p.actions.join(' · '))}</h3><div class="proof-row"><span>Chain</span><b>${p.chainId}</b></div><div class="proof-row"><span>Block</span><b>${p.block}</b></div><p class="small muted">${escape(p.hash)}</p>${config.explorer?`<a href="${escape(config.explorer)}/tx/${escape(p.hash)}" target="_blank" rel="noopener noreferrer">View Explorer</a>`:''}</article>`).join('')+(!proofs.length?notice('当前账户还没有已确认并验证的交易。'):'');
    case 'vault':return top+head('Bell Vault','Encrypted for both of you.')+notice('记忆使用 P-256 ECDH + AES-256-GCM。加密私钥只保存在本机浏览器，公开密钥由钱包签名绑定。当前尚未提供跨设备密钥恢复，请保留首次登记的浏览器。')+btn('管理记忆','story')+`<div class="actions">${btn('导出加密档案','export','','light')}</div>`;
    case 'witness':return top+head('Make It Real','从真实关系开始，逐步形成见证。')+ring(r.status)+notice('目前合约没有 Witness 或 SBT 铸造接口。数字见证与实体订单待接入，不会显示假的 Mint 成功。');
    case 'history':return top+head('Our past Rings')+state.history.map(h=>btn('Ring #'+escape(h.id),'archive',`data-id="${escape(h.id)}"`,'light')).join('')+notice('此列表来自服务端已验证的关系创建交易。尚未接入完整历史事件索引，旧部署历史可能未显示。');
    case 'me':return top+head('Our Ring')+`<div class="card"><div class="proof-row"><span>钱包</span><b>${escape(user)}</b></div><div class="proof-row"><span>状态</span><b>${statusLabel[r.status]}</b></div></div><div class="actions">${btn('修改身份资料','identity')}${btn('Privacy · 隐私设置','privacy','','light')}${btn('Bell Vault','vault','','light')}${btn('Proof History','proofs','','light')}${btn('Witnesses','witness','','light')}${btn('历史 Ring','history','','light')}${r.status==='ACTIVE'?btn('Request End','request-end','','danger'):r.status==='ENDING'?notice('等待另一方确认，或链上七天期限到达。')+(r.requester.toLowerCase()!==chainUser.toLowerCase()?btn('Confirm End','confirm-end','','danger'):'')+(Date.now()/1000>=r.endingAt?btn('Finalize End','finalize-end','','danger'):''):''}${btn('退出钱包会话','logout','','light')}</div>`+banner;
    default:return top+head('Our Ring')+notice('请选择下方页面。');
  }
}
