(() => {
  'use strict';
  const KEY = 'consensus-bell-ui-v1';
  const people = ['Alice', 'Sophie'];
  const interests = ['Music','Travel','Photography','Food','Reading','Movies','AI','Art','Sports'];
  const interestImages = ['music','travel','photo','food','reading','movies','ai','art','sports'];
  const candidates = [
    {name:'Sophie',age:24,city:'Shenzhen',image:'sophie.jpg',tags:['Travel','Music','Photography'],bio:'I love meeting new places and interesting people. Hoping to find someone to explore the world together.'},
  ];
  const fresh = () => ({version:1,actor:'Alice',onboarded:false,profile:{name:'Alice',city:'Shanghai',gender:'Private',age:'20–26',interests:['Travel','Photography','Music'],intention:'Serious relationship',statement:'I believe love is two people growing together, seeing more of the world, and always choosing each other.'},status:'NONE',invitation:null,createdAt:null,endingAt:null,endingBy:null,selectedCandidate:0,saved:[],skipped:[],filter:'All',storyFilter:'all',material:'Rose Gold',privacy:'Only us',memories:[],vows:[],goals:[],proofs:[],witnesses:[],orders:[],notifications:[],selectedVow:null,selectedGoal:null});
  let state = fresh();
  function validSession(s) {
    const text = v => typeof v === 'string';
    const id = v => text(v) && /^[a-z0-9-]{1,80}$/i.test(v);
    const time = v => text(v) && /^\d{4}-\d{2}-\d{2}T/.test(v) && Number.isFinite(Date.parse(v));
    const amount = v => Number.isSafeInteger(v) && v >= 0;
    const image = v => text(v) && (!v || /^assets\/[a-z0-9._-]+$/i.test(v) || /^data:image\/(jpeg|png|webp);base64,[a-z0-9+/=]+$/i.test(v));
    const array = (v,test) => Array.isArray(v) && v.every(test);
    const memory = m => m && id(m.id) && text(m.title) && text(m.text) && ['photo','video','note'].includes(m.type) && people.includes(m.by) && time(m.at) && image(m.image) && (!m.video || /^https?:\/\//i.test(m.video));
    const vow = v => v && id(v.id) && text(v.text) && people.includes(v.by) && time(v.at) && ['PENDING','CONFIRMED'].includes(v.status);
    const goal = g => g && id(g.id) && text(g.title) && text(g.text) && amount(g.target) && g.target > 0 && g.balance && people.every(p=>amount(g.balance[p])) && image(g.image) && (!g.spend || amount(g.spend.amount) && g.spend.amount > 0 && text(g.spend.reason) && people.includes(g.spend.by));
    const record = p => p && id(p.id) && text(p.action) && text(p.entity) && people.includes(p.actor) && time(p.at);
    const witness = w => w && id(w.id) && time(w.at) && ['Rose Gold','Silver','White Gold','Black Titanium'].includes(w.material);
    const order = o => o && id(o.id) && time(o.at) && ['Physical Ring','Memory Object'].includes(o.kind) && text(o.material) && text(o.size) && text(o.engraving);
    if(s?.invitation && !(id(s.invitation.id) && people.includes(s.invitation.from) && people.includes(s.invitation.to) && s.invitation.from !== s.invitation.to && time(s.invitation.expires))) return false;
    return !!(s && s.version === 1 && people.includes(s.actor) && typeof s.onboarded === 'boolean' && s.profile && ['name','city','gender','age','intention','statement'].every(k=>text(s.profile[k])) && array(s.profile.interests,v=>interests.includes(v)) && ['NONE','INVITED','ACTIVE','ENDING','ARCHIVED'].includes(s.status) && (s.status!=='INVITED' || s.invitation && id(s.invitation.id) && people.includes(s.invitation.from) && people.includes(s.invitation.to) && s.invitation.from!==s.invitation.to && time(s.invitation.expires)) && (!['ACTIVE','ENDING','ARCHIVED'].includes(s.status) || time(s.createdAt)) && (s.status!=='ENDING' || time(s.endingAt) && people.includes(s.endingBy)) && amount(s.selectedCandidate) && array(s.saved,text) && array(s.skipped,text) && text(s.filter) && ['all','photo','video','note'].includes(s.storyFilter) && ['Rose Gold','Silver','White Gold','Black Titanium'].includes(s.material) && text(s.privacy) && array(s.memories,memory) && array(s.vows,vow) && array(s.goals,goal) && array(s.proofs,record) && array(s.witnesses,witness) && array(s.orders,order) && array(s.notifications,n=>n && id(n.id) && text(n.title) && people.includes(n.by) && time(n.at)) && (!s.archives || array(s.archives,r=>r && id(r.id) && time(r.createdAt) && time(r.endedAt) && array(r.memories,memory) && array(r.vows,vow) && array(r.goals,goal) && array(r.proofs,record) && array(r.witnesses,witness) && array(r.orders,order))));
  }
  try {const saved = JSON.parse(localStorage.getItem(KEY)); if(validSession(saved)) state = saved;} catch { /* A fresh session remains usable when browser storage is unavailable. */ }
  let route = location.hash.slice(1) || (state.onboarded ? state.status === 'NONE' ? 'path' : state.status === 'INVITED' ? 'sent' : 'home' : 'gateway');
  state.archives ??= [];
  let storyFile = null, modalReturnFocus = null, toastTimer, saveWarning = false;
  const app = document.querySelector('#app'), tabs = document.querySelector('#tabs'), sheet = document.querySelector('#sheet');
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid = () => crypto.randomUUID();
  const date = value => new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
  const today = () => new Date().toISOString();
  const other = () => people.find(p => p !== state.actor);
  const count = () => state.vows.filter(v => v.status === 'CONFIRMED').length;
  const bond = () => state.goals.reduce((n,g) => n + g.balance.Alice + g.balance.Sophie,0);
  const days = () => state.createdAt ? Math.max(1,Math.floor((Date.now()-new Date(state.createdAt).getTime())/86400000)+1) : 0;
  const active = () => state.status === 'ACTIVE';
  const icon = name => {
    const paths = {back:'M15 18l-6-6 6-6',plus:'M12 5v14M5 12h14',close:'M6 6l12 12M18 6L6 18',ring:'M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0z',story:'M4 4h16v16H4zM4 16l5-5 4 4 3-3 4 4M8 8h.01',vow:'M20 5c-3-3-6 0-8 2-2-2-5-5-8-2-4 4 2 10 8 14 6-4 12-10 8-14z',bond:'M4 8h16v12H4zM8 8V4h8v4M9 13h6',me:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM4 21v-2a8 8 0 0 1 16 0v2',arrow:'M9 5l7 7-7 7',check:'M5 12l4 4L19 6',bell:'M6 16V9a6 6 0 0 1 12 0v7l2 2H4l2-2M10 21h4',lock:'M5 10h14v11H5zM8 10V6a4 4 0 0 1 8 0v4',save:'M6 3h12v18l-6-4-6 4z',proof:'M12 3l8 4v6c0 4-8 8-8 8s-8-4-8-8V7l8-4M8 12l3 3 5-6',download:'M12 3v12M7 10l5 5 5-5M4 17v4h16v-4',filter:'M4 6h16M7 12h10M10 18h4'};
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[name] || paths.ring)+'"/></svg>';
  };
  const button = (label,action,extra='',cls='') => '<button class="btn '+cls+'" data-action="'+action+'" '+extra+'>'+label+'</button>';
  const goButton = (label,target,cls='') => button(label,'go','data-to="'+target+'"',cls);
  const avatar = person => '<img class="avatar" src="assets/'+person.toLowerCase()+'.jpg" width="36" height="36" alt="'+person+'">';
  const badge = status => '<span class="pill '+(status === 'CONFIRMED' || status === 'ACTIVE' ? 'ok' : status === 'PENDING' || status === 'ENDING' || status === 'INVITED' ? 'pending' : '')+'"><span class="dot"></span>'+escape(status.toLowerCase().replace(/^./,c=>c.toUpperCase()))+'</span>';
  const ring = (mode=state.status) => '<div class="ring-hero '+({INVITED:'waiting',ENDING:'ending',ARCHIVED:'archived'}[mode] || '')+'" data-material="'+escape(state.material)+'"><img src="assets/ring-float.jpg" width="280" height="280" alt="Your relationship ring"></div>';
  const header = (label,back=true,right='') => '<div class="top">'+(back?'<button class="icon" data-action="back" aria-label="Go back">'+icon('back')+'</button>':'<span class="eyebrow">CONSENSUS BELL</span>')+'<span class="eyebrow">'+escape(label)+'</span>'+right+'</div>';
  const head = (title,sub='') => '<div class="head"><h1>'+title+'</h1>'+(sub?'<p>'+sub+'</p>':'')+'</div>';
  const blank = (title,sub,cta='') => '<div class="blank"><h3>'+title+'</h3><p class="small">'+sub+'</p>'+cta+'</div>';
  function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('on'),3200);}
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{saveWarning=true;toast('Storage is full or unavailable. Export your session before closing.');return false;}}
  function log(action,entity='Ring') {const record={id:uid(),action,entity,actor:state.actor,at:today(),mode:'LOCAL_SIMULATION'};state.proofs.unshift(record);state.notifications.unshift({id:uid(),title:action,by:state.actor,at:record.at,read:false});}
  function navigate(target){closeModal();if(target==='path'&&route==='identity4'){location.hash='creating';setTimeout(()=>{if(route==='creating')navigate('path');},1400);return;}location.hash=target;if(route===target)render();}
  function closeModal(){if(sheet.open)sheet.close();}
  function modal(title,content){modalReturnFocus=document.activeElement;sheet.innerHTML='<div class="dialog-top"><h2 id="sheet-title">'+title+'</h2><button class="icon" data-action="close" aria-label="Close dialog">'+icon('close')+'</button></div>'+content;sheet.showModal();}
  sheet.addEventListener('close',()=>{if(modalReturnFocus?.isConnected)modalReturnFocus.focus();});
  sheet.addEventListener('click',e=>{if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
  function proof(id){const p=state.proofs.find(p=>p.id===id) || state.proofs[0];modal('Proof', '<div class="notice">Local demonstration record. No wallet signature, block, or transaction has been submitted.</div>'+[['Mode','Local UI simulation'],['Action',p?.action||'No record yet'],['Participant',p?.actor||state.actor],['Timestamp',p?new Date(p.at).toLocaleString():'—'],['Record',p?.id||'—'],['Network','Not connected']].map(([k,v])=>'<div class="proof-row"><span>'+k+'</span><b>'+escape(v)+'</b></div>').join('')+(p?.hash?'<div class="proof-row"><span>Content SHA-256</span><b>'+escape(p.hash)+'</b></div>':'')+'<div class="actions">'+button('Close','close','','light')+'</div>');}
  function tabsHtml(){return [['home','ring','Ring'],['story','story','Story'],['vows','vow','Vow'],['bond','bond','Bond'],['me','me','Me']].map(([target,name,label])=>'<button data-action="go" data-to="'+target+'" class="'+(route===target?'active':'')+'" '+(route===target?'aria-current="page"':'')+'>'+icon(name)+label+'</button>').join('');}
  function demoSeed(){state.onboarded=true;state.status='ACTIVE';state.createdAt=new Date(Date.now()-126*86400000).toISOString();state.memories=[{id:uid(),title:'We started our Ring',text:'Two signatures. One shared beginning.',type:'note',by:'Alice',at:state.createdAt,image:''},{id:uid(),title:'East Lake',text:'A perfect day together.',type:'photo',by:'Sophie',at:today(),image:'assets/east-lake.jpg'},{id:uid(),title:'First movie together',text:'So many laughs.',type:'photo',by:'Alice',at:today(),image:'assets/cinema.jpg'}];state.vows=['Let’s always communicate, even when it’s hard.','Travel to Japan together.','Support each other’s dreams.','Morning walks together, every Sunday.','We save before we spend.','No going to bed angry.','Learn to say sorry first.'].map(t=>({id:uid(),text:t,by:'Alice',at:state.createdAt,status:'CONFIRMED'}));state.vows.push({id:uid(),text:'I choose you, again, in all the ordinary days and all the unexpected ones.',by:'Alice',at:today(),status:'PENDING'});state.goals=[{id:uid(),title:'Japan Trip',text:'A journey to see more of the world together.',target:1000,balance:{Alice:100,Sophie:100},image:'assets/japan-trip.jpg',spend:null},{id:uid(),title:'Anniversary',text:'Make our next milestone special.',target:500,balance:{Alice:30,Sophie:30},image:'assets/anniversary.jpg',spend:null},{id:uid(),title:'Future Home',text:'Build a little world of our own.',target:5000,balance:{Alice:0,Sophie:0},image:'assets/future-home.jpg',spend:null}];log('Demo relationship opened');persist();navigate('home');}
  const labelInput = (label,name,value='',type='text',attrs='') => '<label for="f-'+name+'">'+label+'</label><input id="f-'+name+'" name="'+name+'" type="'+type+'" value="'+escape(value)+'" '+attrs+'>';
  const noteInput = (label,name,value='',max=200) => '<label for="f-'+name+'">'+label+'</label><textarea id="f-'+name+'" name="'+name+'" maxlength="'+max+'">'+escape(value)+'</textarea>';
  const submit = label => '<div class="actions"><button class="btn" type="submit">'+label+'</button></div>';
  function onboarding(step){const p=state.profile;let content='';if(step===1)content=head('Who are you?','Let’s create your identity.')+'<div class="center">'+avatar(state.actor)+'</div>'+labelInput('Nickname','name',p.name,'text','required maxlength="16"')+labelInput('City','city',p.city,'text','required maxlength="40"')+'<label for="f-gender">Gender</label><select id="f-gender" name="gender">'+['Private','Female','Male','Non-binary'].map(v=>'<option '+(p.gender===v?'selected':'')+'>'+v+'</option>').join('')+'</select><label for="f-age">Age range</label><select id="f-age" name="age">'+['20–26','27–33','34–40','41+','Prefer not to say'].map(v=>'<option '+(p.age===v?'selected':'')+'>'+v+'</option>').join('')+'</select>';if(step===2)content=head('What do you love?','Choose up to eight things you enjoy.')+'<div class="interests">'+interests.map((v,i)=>'<button type="button" class="interest '+(p.interests.includes(v)?'selected':'')+'" aria-pressed="'+p.interests.includes(v)+'" data-action="interest" data-value="'+v+'"><img src="assets/in-'+interestImages[i]+'.jpg" width="110" height="108" alt=""><span>'+v+'</span></button>').join('')+'</div><p class="small muted" style="margin-top:16px">'+p.interests.length+' / 8 selected</p>';if(step===3)content=head('What do you seek?','Your relationship intention.')+[['Serious relationship','Looking for a long-term partner.'],['Open to connection','Meet and see where it goes.'],['Already in love','I want to bind my person.'],['Just exploring','For now, I’m just looking around.']].map(([v,s],i)=>'<div class="radio-card"><input type="radio" id="intent-'+i+'" name="intention" value="'+v+'" '+(p.intention===v?'checked':'')+'><label for="intent-'+i+'">'+v+'<p>'+s+'</p></label></div>').join('');if(step===4)content=head('What does love mean to you?','Share a few words about yourself.')+noteInput('Your love statement','statement',p.statement,200)+'<p class="small muted" id="statement-count">'+p.statement.length+' / 200</p>';return header('Create identity')+'<div class="row gap"><div class="progress"><span style="width:'+step*25+'%"></span></div><span class="small muted">'+step+' / 4</span></div><form class="form" data-form="identity" data-step="'+step+'">'+content+submit(step===4?'Create My Identity':'Next')+'</form>';}
  function story(){const list=state.memories.filter(m=>state.storyFilter==='all'||m.type===state.storyFilter).slice().sort((a,b)=>new Date(b.at)-new Date(a.at));return header('Story',false,'<button class="icon" data-action="add-memory" aria-label="Add a memory">'+icon('plus')+'</button>')+head('Our Story','All the moments, big or small.')+'<div class="chips">'+[['all','All'],['photo','Photos'],['video','Videos'],['note','Notes']].map(([v,l])=>'<button class="chip '+(state.storyFilter===v?'active':'')+'" data-action="story-filter" data-value="'+v+'">'+l+'</button>').join('')+'</div>'+(list.length?'<div class="timeline">'+list.map(m=>'<article class="event"><p class="small muted">'+date(m.at)+' · '+escape(m.by)+'</p><button class="title" data-action="memory" data-id="'+m.id+'">'+escape(m.title)+'</button><p class="small muted">'+escape(m.text)+'</p>'+(m.image?'<img class="photo" src="'+escape(m.image)+'" width="300" height="160" alt="'+escape(m.title)+'" loading="lazy">':'')+'</article>').join('')+'</div>':blank('A story waiting to be written','Keep a little piece of today.',button('Add a memory','add-memory')));}
  function vows(){return header('Vows',false)+head('Our Vows','A thought becomes a Vow only when both of you choose it.')+'<div class="row"><p><strong>'+count()+'</strong> <span class="small muted">Total Vows</span></p>'+button('+ New Vow','new-vow','','compact')+'</div><div class="stack" style="margin-top:20px">'+state.vows.map(v=>'<button class="card flat" style="text-align:left;margin:0" data-action="vow" data-id="'+v.id+'"><p class="quote" style="margin:0 0 12px">“'+escape(v.text)+'”</p><div class="row">'+badge(v.status)+'<span class="small muted">'+(v.status==='PENDING'?'Waiting for '+escape(v.by==='Alice'?'Sophie':'Alice'):date(v.at))+'</span></div></button>').join('')+'</div>'+(!state.vows.length?blank('A promise starts here','Something you both choose, freely.'):'');}
  function vowDetail(){const v=state.vows.find(v=>v.id===state.selectedVow);if(!v)return blank('Vow not found','Choose a vow from your collection.',goButton('Our Vows','vows'));return header('Vow')+'<img class="photo" src="assets/vow-hero.jpg" width="340" height="220" alt="A quiet moment together"><p class="quote">“'+escape(v.text)+'”</p><div class="row"><span class="small muted">Proposed by '+escape(v.by)+'<br>'+date(v.at)+'</span>'+badge(v.status)+'</div><div class="actions">'+(v.status==='PENDING'?v.by===state.actor?'<div class="notice">Waiting for '+escape(other())+'. Only the other participant can confirm this vow.</div>':button('Confirm','confirm-vow','data-id="'+v.id+'"'):'<div class="card center"><p style="color:var(--green)">'+icon('check')+' Confirmed by Alice & Sophie</p></div>')+button('View local record','proof')+'</div>';}
  function goalCard(g){const total=g.balance.Alice+g.balance.Sophie;return '<article class="card">'+(g.image?'<img class="goal-img" src="'+g.image+'" width="300" height="144" alt="'+escape(g.title)+'">':'')+'<h2>'+escape(g.title)+'</h2><p class="small muted">'+escape(g.text)+'</p><div class="row" style="margin-top:16px"><div class="avatars">'+avatar('Alice')+avatar('Sophie')+'</div><span class="small"><b>'+total+'</b> / '+g.target.toLocaleString()+' BOT</span></div><div class="meter"><span style="--fill:'+Math.min(1,total/g.target)+'"></span></div>'+button('Open goal','goal','data-id="'+g.id+'"','light')+'</article>';}
  function goals(){return header('Bond',false,'<button class="icon" data-action="new-goal" aria-label="Create goal">'+icon('plus')+'</button>')+head('Our Bond','Give a future plan some weight.')+state.goals.map(goalCard).join('')+(!state.goals.length?blank('A future worth saving for','Create a shared goal. Each contribution remains yours.',button('Create a goal','new-goal')):'')+'<p class="small muted center">Demo BOT · contributions are stored locally.</p>';}
  function goalDetail(){const g=state.goals.find(g=>g.id===state.selectedGoal);if(!g)return blank('Choose a goal','Make a little room for your future.',goButton('Our Bond','bond'));const total=g.balance.Alice+g.balance.Sophie;return header('Our goal')+head(escape(g.title),escape(g.text))+goalCard(g)+'<div class="card"><h3>Your contributions</h3>'+people.map(p=>'<div class="proof-row"><span>'+p+'</span><b>'+g.balance[p]+' BOT</b></div>').join('')+'<p class="small muted" style="margin-top:12px">Joint spending requires both participants. Remaining contributions can be withdrawn after archival.</p></div>'+(g.spend?'<div class="card"><h3>Spending request</h3><p>'+g.spend.amount+' BOT · '+escape(g.spend.reason)+'</p><p class="small muted">Requested by '+g.spend.by+'</p>'+(g.spend.by!==state.actor?button('Confirm shared expense','confirm-spend'):badge('PENDING'))+'</div>':'')+'<div class="actions">'+(active()?button('Deposit demo BOT','deposit')+(total?button('Request shared expense','spend','','light'):''):state.status==='ARCHIVED'&&g.balance[state.actor]?button('Withdraw my '+g.balance[state.actor]+' BOT','withdraw'):'<div class="notice">Contributions are paused while the Ring is ending or archived.</div>')+'</div>';}
  function home(){return header('Our Ring',false,'<button class="icon" data-action="go" data-to="notifications" aria-label="Notifications">'+icon('bell')+'</button>')+'<div class="center"><p class="muted">Alice × Sophie</p><div style="margin:8px 0">'+badge(state.status)+'</div><p class="number">'+days()+'</p><p class="small muted">Days Together</p>'+ring()+'</div><div class="stats">'+[['story',state.memories.length,'Memories'],['vows',count(),'Vows'],['bond',bond(),'BOT Bond']].map(([r,n,l])=>'<button data-action="go" data-to="'+r+'"><strong>'+n+'</strong><span>'+l+'</span></button>').join('')+'</div><div class="today"><h3>Today</h3><div class="card">'+(state.vows.some(v=>v.status==='PENDING')?'<button class="list-row" data-action="go" data-to="vows"><div><p>A Vow is waiting.</p><p class="small muted">A little promise, for both of you.</p></div>'+icon('arrow')+'</button>':'<p class="small muted">A little time together is enough.</p>')+'<button class="list-row" data-action="add-memory"><div><p>Keep a piece of today</p><p class="small muted">Add to your shared story.</p></div>'+icon('plus')+'</button></div></div>'+(state.status==='ENDING'?'<div class="notice">Ending requested. '+date(new Date(new Date(state.endingAt).getTime()+7*86400000))+' is the timeout date.</div>':state.status==='ARCHIVED'?'<div class="notice">Some things end. That doesn’t mean they never existed.</div>':'');}
  function witness(){return header('Witness')+head('Make It Real','Turn our Ring into something real.')+[['digital','Digital Ring','Mint a unique digital witness from your relationship.','ring-float.jpg'],['physical','Physical Ring','A jewelry design generated from your Ring.','ring-box.jpg'],['object','Memory Object','A tangible piece of your love story.','keepsake.jpg']].map(([v,t,s,img])=>'<article class="card witness-card"><img src="assets/'+img+'" width="340" height="200" alt="'+t+'"><div class="body"><h2>'+t+'</h2><p>'+s+'</p>'+button('Explore','witness','data-value="'+v+'"','light')+'</div></article>').join('')+goButton('My witnesses & order drafts','collection','light');}
  let witnessType='digital';
  function witnessDetail(){return header('Witness detail')+ring()+head('Your Unique Ring','Generated from your relationship.')+'<div class="card">'+[['Days Together',days()],['Memories',state.memories.length],['Confirmed Vows',count()],['BOT Bond',bond()]].map(([l,v])=>'<div class="proof-row"><span>'+l+'</span><b>'+v+'</b></div>').join('')+'</div><p class="small muted">Material · '+escape(state.material)+'</p><div class="materials">'+['Rose Gold','Silver','White Gold','Black Titanium'].map(v=>'<button class="material '+(state.material===v?'active':'')+'" data-action="material" data-value="'+v+'" aria-label="'+v+'" aria-pressed="'+(state.material===v)+'"></button>').join('')+'</div><div class="actions">'+(witnessType==='digital'?button('Create demo digital witness','mint'):button('Configure '+(witnessType==='physical'?'Physical Ring':'Memory Object'),'order'))+'<p class="small muted center">'+(witnessType==='digital'?'Local collectible only. No NFT is minted.':'Save a design draft. No payment or order is submitted.')+'</p></div>';}
  function me(){return header('Settings',false)+head('Our Ring')+'<div class="card">'+[['Status',state.status],['Created',state.createdAt?date(state.createdAt):'Not created'],['Participants','Alice · Sophie'],['Current demo user',state.actor]].map(([k,v])=>'<div class="proof-row"><span>'+k+'</span><b>'+escape(v)+'</b></div>').join('')+'</div><div class="card">'+[['privacy','lock','Privacy','Manage profile visibility'],['vault','download','Bell Vault','Manage & export local memories'],['history','proof','Proof History','Your local activity records'],['witness','ring','Witnesses','Digital and physical designs'],['profile','me','Your identity','Profile and interests']].map(([r,i,t,s])=>'<button class="list-row" data-action="go" data-to="'+r+'">'+icon(i)+'<div><p>'+t+'</p><p class="small muted">'+s+'</p></div>'+icon('arrow')+'</button>').join('')+'</div><div class="actions">'+(state.status!=='ARCHIVED'?goButton('End Our Ring','ending','danger'):goButton('Begin a new chapter','path','light'))+button('Export local session','export','','light')+button('Reset local demo','reset','','light')+'</div>';}
  function ending(){return header('Our Ring')+head('A gentle ending','Ending a Ring does not erase its history.')+ring()+ '<p class="quote center">Some things end.<br>That doesn’t mean they never existed.</p><div class="card"><p>Your memories and vows remain. Each person can withdraw their own remaining contribution after archival.</p></div><div class="actions">'+(state.status==='ACTIVE'?button('Request End','request-end','','danger'):state.status==='ENDING'?'<div class="notice">Requested by '+state.endingBy+' on '+date(state.endingAt)+'. The other participant can confirm now, or archival becomes available after seven days.</div>'+(state.actor!==state.endingBy?button('Confirm End & Archive','confirm-end','','danger'):'')+(Date.now()>=new Date(state.endingAt).getTime()+7*86400000?button('Finalize after seven days','finalize-end','','danger'):''):badge('ARCHIVED'))+'</div>';}
  function discover(){const list=candidates.filter(c=>!state.skipped.includes(c.name)&&(state.filter==='All'||c.city===state.filter));const c=list[state.selectedCandidate%Math.max(1,list.length)];if(!c)return header('Discover')+head('People who might resonate')+blank('You’ve seen today’s recommendations','A thoughtful few, rather than an endless feed.',button('Show recommendations again','clear-skips'));return header('Discover',true,'<button class="icon" data-action="filters" aria-label="Discovery filters">'+icon('filter')+'</button>')+head('People who might resonate','A thoughtful introduction. A mutual choice.')+'<div class="card"><img class="photo tall" src="assets/'+c.image+'" width="300" height="270" alt="'+c.name+'"><h2 style="margin-top:16px">'+c.name+', '+c.age+'</h2><p class="small muted">'+c.city+'</p><div class="chips">'+c.tags.map(t=>'<span class="pill">'+t+'</span>').join('')+'</div><p class="small muted">'+c.bio+'</p><p class="small" style="margin:16px 0">'+c.tags.filter(t=>state.profile.interests.includes(t)).length+' shared interests · Same intention</p><div class="row">'+button('Skip','skip','data-value="'+c.name+'"','light compact')+button(state.saved.includes(c.name)?'Saved':'Save','save','data-value="'+c.name+'"','light compact')+goButton('Ring','invite','compact')+'</div></div><p class="small muted center">'+list.length+' recommendations · '+state.saved.length+' saved</p>';}
  function pages(){
    if(/^identity[1-4]$/.test(route))return onboarding(Number(route.at(-1)));
    switch(route){
      case 'gateway':return '<section class="gateway">'+header('',false)+'<div>'+ring('NONE')+head('Forever begins<br>with one mutual yes.','Two signatures. One ring.<br>A shared history.')+'</div><div class="actions">'+goButton('Begin','identity1')+button('Explore Alice & Sophie’s Ring','seed','','light')+'<p class="small muted">Local UI edition · ready for service integration</p></div></section>';
      case 'creating':return header('Creating identity',false)+ring('NONE')+head('Creating your identity…','A little space, just for you.')+'<p class="small muted center">Saving your local profile.</p>';
      case 'path':return header('Choose path')+head('What’s your situation<br>right now?')+[['discover','Find Someone','I haven’t met my person yet.','find-someone.jpg'],['invite','Bind My Person','We already found each other.','bind-person.jpg']].map(([r,t,s,img])=>'<button class="path-card" data-action="go" data-to="'+r+'"><img src="assets/'+img+'" width="340" height="240" alt=""><h2>'+t+'</h2><p>'+s+'</p></button>').join('');
      case 'discover':return discover();
      case 'invite':return header('Invitation')+ring('INVITED')+head('Send a Ring Invitation','A Ring belongs to two people. Only two.')+'<div class="card center"><div class="avatars" style="justify-content:center">'+avatar('Alice')+avatar('Sophie')+'</div><p style="margin:12px 0">'+state.actor+' × '+other()+'</p><p class="small muted">This local demo uses Alice and Sophie. A real invitation requires connected accounts.</p></div><div class="actions">'+button('Send Invitation','invite')+'</div>';
      case 'sent':return header('Invitation')+ring('INVITED')+head('Invitation Sent','Waiting for '+(state.invitation?.to||other())+'.')+'<div class="card"><p class="small muted">Expires in</p><p id="countdown">'+countdown()+'</p></div><div class="actions">'+button('Share Invitation','share')+button('View local record','proof','','light')+button('Cancel Invitation','cancel-invite','','light')+button('Switch to recipient','recipient','','light')+'</div>';
      case 'received':return header('Invitation')+ring('INVITED')+head((state.invitation?.from||other())+' wants to share<br>a Ring with you.')+'<div class="card"><p class="quote">'+escape(state.profile.statement)+'</p><div class="chips">'+state.profile.interests.map(t=>'<span class="pill">'+escape(t)+'</span>').join('')+'</div></div><div class="actions">'+goButton('Accept','sign')+button('Decline','decline','','light')+'</div>';
      case 'sign':return header('Sign & Accept')+ring()+head('Only you can<br>complete this Ring.')+'<div class="card"><p>Creates one active Romantic Ring</p><p>No funds transferred</p><p>Requires the invited participant</p></div><div class="notice">This confirms locally in the demo. Connect a wallet and deployed contracts for a real signature.</div><div class="actions">'+button('Accept in local demo','accept')+'</div>';
      case 'ceremony':return '<div class="ceremony">'+ring('ACTIVE')+'<h1>Our Ring</h1><p style="margin:16px">Alice × Sophie<br><span class="small muted">Born '+date(state.createdAt)+'</span></p><p class="quote">Forever does not begin with a promise.<br>It begins with two people choosing the same thing.</p><div class="actions">'+goButton('Enter Our Ring','home')+'</div></div>';
      case 'home':return home();case 'story':return story();case 'vows':return vows();case 'vow-detail':return vowDetail();case 'bond':return goals();case 'goal':return goalDetail();case 'me':return me()+button('Past Rings','archives','','light');case 'ending':return ending();case 'witness':return witness();case 'witness-detail':return witnessDetail();
      case 'vault':return header('Bell Vault')+head('Bell Vault','Your memories, kept on this device.')+'<div class="card"><h2>Our Memories</h2><div class="stats">'+[['Photos','photo'],['Videos','video'],['Notes','note']].map(([l,t])=>'<div><strong>'+state.memories.filter(m=>m.type===t).length+'</strong><span>'+l+'</span></div>').join('')+'</div><p class="small muted">'+count()+' confirmed vows · '+state.witnesses.length+' digital witnesses</p></div><div class="actions">'+goButton('Manage Memories','story')+button('Export Archive','export','','light')+button('Backup local session','backup','','light')+'</div><div class="notice">UI edition: memories are stored locally without encryption. The production architecture uses client encryption for private memories and public hashes for proofs.</div>';
      case 'privacy':return header('Privacy')+head('Your little world','Choose who can see your demo profile.')+'<form class="form" data-form="privacy">'+['Only us','Discoverable profile','Private profile'].map((v,i)=>'<div class="radio-card"><input id="privacy-'+i+'" type="radio" name="privacy" value="'+v+'" '+(state.privacy===v?'checked':'')+'><label for="privacy-'+i+'">'+v+'</label></div>').join('')+submit('Save preference')+'</form><div class="notice">This changes the local preference. No remote profile or account permissions are changed.</div>';
      case 'profile':return header('Identity')+head(escape(state.profile.name),escape(state.profile.city)+' · '+escape(state.profile.age))+'<div class="card"><p class="quote">'+escape(state.profile.statement)+'</p><div class="chips">'+state.profile.interests.map(t=>'<span class="pill">'+escape(t)+'</span>').join('')+'</div><p class="small muted">'+escape(state.profile.intention)+'</p></div>'+goButton('Edit identity','identity1');
      case 'history':return header('Proof history')+head('A shared record','Local actions, kept in order.')+state.proofs.map(p=>'<button class="list-row" data-action="proof" data-id="'+p.id+'"><div><p>'+escape(p.action)+'</p><p class="small muted">'+escape(p.actor)+' · '+date(p.at)+'</p></div>'+icon('arrow')+'</button>').join('')+(!state.proofs.length?blank('No records yet','Your mutual actions will appear here.'):'');
      case 'notifications':return header('Notifications')+head('Little updates')+state.notifications.map(n=>'<div class="card"><p>'+escape(n.title)+'</p><p class="small muted">'+escape(n.by)+' · '+date(n.at)+'</p></div>').join('')+(!state.notifications.length?blank('All quiet','You’re up to date.'):'');
      case 'collection':return header('Your witnesses')+head('Made from your story')+state.witnesses.map(w=>'<div class="card"><h3>Digital Witness</h3><p>'+escape(w.material)+' · '+date(w.at)+'</p><p class="small muted">Alice & Sophie · mirrored local collectible</p><p class="small muted">'+escape(w.id)+'</p></div>').join('')+state.orders.map(o=>'<div class="card"><h3>'+escape(o.kind)+' · Draft</h3><p>'+escape(o.material)+' · Size '+escape(o.size)+'</p><p class="small muted">'+escape(o.engraving)+'</p></div>').join('')+(!state.witnesses.length&&!state.orders.length?blank('A story taking shape','Create a digital witness or save a physical design.',goButton('Make It Real','witness')):'');
      default:return header('Consensus Bell')+blank('Find your way home','This page does not exist.',goButton('Continue',state.onboarded?'path':'gateway'));
    }
  }
  function render(){if(state.status==='INVITED'&&state.invitation&&Date.now()>new Date(state.invitation.expires).getTime()){state.status='NONE';state.invitation=null;persist();route='path';history.replaceState(null,'','#path');}const relationRoutes=['home','story','vows','vow-detail','bond','goal','me','vault','ending','witness','witness-detail','collection','history'];if(relationRoutes.includes(route)&&!['ACTIVE','ENDING','ARCHIVED'].includes(state.status)){route=state.status==='INVITED'?'sent':'path';history.replaceState(null,'','#'+route);}app.innerHTML='<div class="page">'+pages()+'</div>';tabs.innerHTML=relationRoutes.includes(route)?tabsHtml():'';document.querySelector('#actor-toggle').textContent=state.actor+' ⇄ '+other();document.title='Consensus Bell · '+route.replaceAll('-',' ');app.scrollTop=0;}
  function countdown(){if(!state.invitation)return 'No pending invitation';const left=Math.max(0,Math.floor((new Date(state.invitation.expires)-Date.now())/1000));return [Math.floor(left/3600),Math.floor(left%3600/60),left%60].map(n=>String(n).padStart(2,'0')).join(':');}
  function requireActive(){if(active())return true;toast('This action is available while your Ring is active.');return false;}
  function exportData(){const data={format:'Consensus Bell Local UI Archive',encrypted:false,exportedAt:today(),session:state};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='consensus-bell-archive-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Local archive downloaded.');}
  function newMemory(){if(!requireActive())return;storyFile=null;modal('Keep a memory','<form class="form" data-form="memory">'+labelInput('Title','title','','text','required maxlength="80"')+noteInput('A little note','text','',600)+'<label for="f-type">Type</label><select id="f-type" name="type"><option value="note">Note</option><option value="photo">Photo</option><option value="video">Video note / link</option></select>'+labelInput('Date','date',new Date().toISOString().slice(0,10),'date','required')+'<label for="f-image">Photo (JPEG, PNG, WebP; up to 1 MB)</label><input id="f-image" name="image" type="file" accept="image/jpeg,image/png,image/webp"><p id="file-status" class="small muted"></p>'+labelInput('Optional video URL','video','','url')+'<div class="check"><input id="f-anchor" type="checkbox" name="anchor"><label for="f-anchor">Compute a content proof (local SHA-256; not submitted on-chain)</label></div>'+submit('Save memory')+'</form>');}
  function goalForm(action){const g=state.goals.find(g=>g.id===state.selectedGoal);if(!g||!requireActive())return;modal(action==='deposit'?'Add to our future':'A shared expense','<form class="form" data-form="'+action+'"><p class="small muted">'+escape(g.title)+' · acting as '+state.actor+'</p>'+labelInput('Amount · demo BOT','amount',action==='deposit'?'50':'','number','required min="1" max="1000000" step="1"')+(action==='spend'?labelInput('What is it for?','reason','','text','required maxlength="120"'):'<div class="notice">Your contribution is recorded in your name. No real funds are transferred.</div>')+submit(action==='deposit'?'Deposit demo BOT':'Request both signatures')+'</form>');}
  document.addEventListener('click',async e=>{const target=e.target.closest('[data-action]');if(!target)return;const a=target.dataset.action,v=target.dataset.value,id=target.dataset.id;
    if(a==='close'){closeModal();return;}if(a==='go'){if(target.dataset.to==='path'&&state.status==='ARCHIVED'){modal('Begin a new chapter','<p>Your archived Ring will stay in Past Rings. Its memories, vows and contribution records will be preserved.</p><div class="actions">'+button('Begin a new Ring','new-chapter')+button('Keep viewing this Ring','close','','light')+'</div>');return;}navigate(target.dataset.to);return;}if(a==='back'){navigate(['goal','vow-detail','vault','witness','witness-detail','collection','history','privacy','ending','profile','notifications'].includes(route)?({goal:'bond','vow-detail':'vows','witness-detail':'witness',collection:'witness'}[route]||'me'):/identity/.test(route)?Number(route.at(-1))>1?'identity'+(Number(route.at(-1))-1):'gateway':'path');return;}
    if(a==='new-chapter'){if(state.status!=='ARCHIVED')return;if(bond()>0){toast('Both participants must withdraw their remaining contributions first.');return;}state.archives.push({id:uid(),createdAt:state.createdAt,endedAt:today(),memories:state.memories,vows:state.vows,goals:state.goals,proofs:state.proofs,witnesses:state.witnesses,orders:state.orders});Object.assign(state,{status:'NONE',invitation:null,createdAt:null,endingAt:null,endingBy:null,memories:[],vows:[],goals:[],proofs:[],witnesses:[],orders:[]});persist();navigate('path');return;}
    if(a==='archives'){modal('Past Rings',state.archives.length?state.archives.map(r=>'<div class="card"><h3>Our Ring · '+date(r.createdAt)+'</h3><p class="small muted">Archived '+date(r.endedAt)+'</p>'+r.memories.map(m=>'<div class="summary"><p>'+escape(m.title)+'</p><p class="small muted">'+escape(m.text)+'</p>'+(m.image?'<img class="photo" src="'+escape(m.image)+'" width="300" height="160" alt="'+escape(m.title)+'">':'')+'</div>').join('')+r.vows.map(v=>'<p class="small">“'+escape(v.text)+'” · '+escape(v.status)+'</p>').join('')+'</div>').join(''):blank('No archived chapters yet','Your Ring history stays with you.'));return;}
    if(a==='seed'){demoSeed();return;}if(a==='interest'){const p=state.profile;if(p.interests.includes(v))p.interests=p.interests.filter(t=>t!==v);else if(p.interests.length<8)p.interests.push(v);else{toast('Choose up to eight interests.');return;}persist();render();return;}
    if(a==='invite'){if(state.status!=='NONE'){toast('You already have a pending or active Ring.');return;}state.invitation={id:uid(),from:state.actor,to:other(),expires:new Date(Date.now()+86400000).toISOString()};state.status='INVITED';log('Invitation created');persist();navigate('sent');return;}
    if(a==='recipient'){state.actor=state.invitation?.to||other();persist();navigate('received');return;}if(a==='cancel-invite'||a==='decline'){if(!state.invitation)return;if(a==='cancel-invite'&&state.actor!==state.invitation.from||a==='decline'&&state.actor!==state.invitation.to){toast('Switch to the correct participant first.');return;}state.invitation=null;state.status='NONE';log(a==='decline'?'Invitation declined':'Invitation cancelled');persist();navigate('path');return;}
    if(a==='share'){const text='Consensus Bell local demo invitation '+(state.invitation?.id||'')+'. Open this App on this device and switch to '+(state.invitation?.to||other())+'.';try{await navigator.clipboard.writeText(text);toast('Demo invitation copied. It works on this device only.');}catch{modal('Share invitation','<p>'+escape(text)+'</p>');}return;}
    if(a==='accept'){if(state.status!=='INVITED'||!state.invitation||state.actor!==state.invitation.to){toast('Only the invited participant can accept.');return;}if(Date.now()>=new Date(state.invitation.expires).getTime()){toast('This invitation has expired.');render();return;}state.status='ACTIVE';state.createdAt=today();state.endingAt=null;state.endingBy=null;state.vows=[];state.memories=[{id:uid(),title:'We started our Ring',text:'Two people choosing the same thing.',type:'note',by:state.actor,at:today(),image:''}];state.goals=[];log('Ring mutually accepted');persist();navigate('ceremony');return;}
    if(a==='proof'){proof(id);return;}if(a==='story-filter'){state.storyFilter=v;persist();render();return;}if(a==='add-memory'){newMemory();return;}
    if(a==='memory'){const m=state.memories.find(m=>m.id===id);if(!m)return;modal(escape(m.title),(m.image?'<img class="photo" src="'+escape(m.image)+'" width="320" height="220" alt="'+escape(m.title)+'">':'')+'<p class="quote">'+escape(m.text)+'</p><p class="small muted">'+escape(m.by)+' · '+date(m.at)+'</p>'+(m.video?'<a href="'+escape(m.video)+'" target="_blank" rel="noopener noreferrer">Open video</a>':'')+(m.hash?'<div class="notice">Content SHA-256<br>'+escape(m.hash)+'</div>':'')+'<div class="actions">'+button('Close','close','','light')+'</div>');return;}
    if(a==='new-vow'){if(!requireActive())return;modal('A thought, for both of you','<form class="form" data-form="vow">'+noteInput('Your Vow','text','',200)+'<p class="small muted">Only '+other()+' can confirm your proposal.</p>'+submit('Propose Vow')+'</form>');return;}if(a==='vow'){state.selectedVow=id;persist();navigate('vow-detail');return;}
    if(a==='confirm-vow'){const vow=state.vows.find(v=>v.id===id);if(!requireActive()||!vow||vow.status!=='PENDING')return;if(vow.by===state.actor){toast('The other participant must confirm.');return;}vow.status='CONFIRMED';vow.confirmedAt=today();log('Vow confirmed','Vow');persist();render();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced){app.querySelector('.page').animate([{opacity:.4,transform:'scale(.985)'},{opacity:1,transform:'scale(1)'}],{duration:400});}toast('Both chose it. '+count()+' confirmed vows.');return;}
    if(a==='new-goal'){if(!requireActive())return;modal('Give a future plan some weight','<form class="form" data-form="goal">'+labelInput('Goal name','title','','text','required maxlength="60"')+noteInput('What are we saving for?','text','',200)+labelInput('Target · demo BOT','target','1000','number','required min="1" max="1000000" step="1"')+submit('Create shared goal')+'</form>');return;}
    if(a==='goal'){state.selectedGoal=id;persist();navigate('goal');return;}if(a==='deposit'||a==='spend'){goalForm(a);return;}
    if(a==='confirm-spend'){const g=state.goals.find(g=>g.id===state.selectedGoal);if(!requireActive()||!g?.spend||g.spend.by===state.actor)return;const total=g.balance.Alice+g.balance.Sophie;if(g.spend.amount>total){toast('There is not enough in this goal.');return;}const aliceShare=Math.round(g.spend.amount*g.balance.Alice/total);g.balance.Alice-=aliceShare;g.balance.Sophie-=g.spend.amount-aliceShare;log('Shared expense confirmed','Bond');g.spend=null;persist();render();return;}
    if(a==='withdraw'){const g=state.goals.find(g=>g.id===state.selectedGoal);if(!g||state.status!=='ARCHIVED')return;const amount=g.balance[state.actor];g.balance[state.actor]=0;log('Own remaining contribution withdrawn','Bond');persist();render();toast(amount+' demo BOT returned to '+state.actor+'.');return;}
    if(a==='witness'){witnessType=v;navigate('witness-detail');return;}if(a==='material'){state.material=v;persist();render();return;}if(a==='mint'){if(!requireActive())return;modal('Digital witness','<p>Save mirrored local collectibles for Alice and Sophie in '+escape(state.material)+'.</p><div class="notice">This is a UI demo. No payment or on-chain mint.</div><div class="actions">'+button('Create local witness','mint-confirm')+'</div>');return;}if(a==='mint-confirm'){if(!requireActive())return;state.witnesses.push({id:uid(),at:today(),material:state.material,participants:people,snapshot:{days:days(),memories:state.memories.length,vows:count(),bond:bond()}});log('Digital witness created locally','Witness');persist();navigate('collection');return;}
    if(a==='order'){if(!requireActive())return;modal('Make it yours','<form class="form" data-form="order"><p>'+escape(state.material)+' · '+(witnessType==='physical'?'Physical Ring':'Memory Object')+'</p>'+labelInput('Size / dimensions','size','US 7','text','required maxlength="30"')+labelInput('Engraving','engraving','Alice × Sophie','text','maxlength="60"')+'<div class="notice">Save a design draft, without checkout or delivery information.</div>'+submit('Save design draft')+'</form>');return;}
    if(a==='request-end'){if(!requireActive())return;modal('Request an ending','<p>Ask '+other()+' to confirm. Your Ring can be archived immediately by mutual choice, or finalized after seven days.</p><div class="actions">'+button('Request End','end-submit','','danger')+button('Keep our Ring','close','','light')+'</div>');return;}if(a==='end-submit'){if(!requireActive())return;state.status='ENDING';state.endingAt=today();state.endingBy=state.actor;log('Ring ending requested');persist();closeModal();render();return;}if(a==='confirm-end'||a==='finalize-end'){if(state.status!=='ENDING')return;if(a==='confirm-end'&&state.actor===state.endingBy||a==='finalize-end'&&Date.now()<new Date(state.endingAt).getTime()+7*86400000){toast('The other participant or the seven-day timeout is required.');return;}state.status='ARCHIVED';state.goals.forEach(g=>g.spend=null);log('Ring archived');persist();navigate('home');return;}
    if(a==='export'||a==='backup'){exportData();return;}if(a==='reset'){modal('Reset this local demo?','<p>Your local identity, memories, vows and demo balances will be removed. Export them first if you want to keep them.</p><div class="actions">'+button('Export first','export','','light')+button('Reset local data','reset-confirm','','danger')+button('Cancel','close','','light')+'</div>');return;}if(a==='reset-confirm'){state=fresh();state.archives=[];persist();navigate('gateway');return;}
    if(a==='filters'){modal('Find your kind of connection','<div class="stack">'+['All','Shanghai','Shenzhen','Hangzhou'].map(c=>button(c,'filter','data-value="'+c+'"',state.filter===c?'':'light')).join('')+'</div>');return;}if(a==='filter'){state.filter=v;state.selectedCandidate=0;persist();closeModal();render();return;}if(a==='skip'){state.skipped.push(v);state.selectedCandidate=0;persist();render();return;}if(a==='save'){state.saved=state.saved.includes(v)?state.saved.filter(x=>x!==v):[...state.saved,v];persist();render();return;}if(a==='clear-skips'){state.skipped=[];persist();render();return;}
  });
  document.addEventListener('submit',async e=>{const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();const data=new FormData(form),value=k=>String(data.get(k)||'').trim(),type=form.dataset.form;
    if(type==='identity'){const step=Number(form.dataset.step);if(step===1){if(!value('name')||!value('city')){toast('Add your nickname and city.');return;}Object.assign(state.profile,{name:value('name'),city:value('city'),gender:value('gender'),age:value('age')});}if(step===2&&!state.profile.interests.length){toast('Choose at least one interest.');return;}if(step===3)state.profile.intention=value('intention');if(step===4){if(!value('statement')){toast('Share a few words about love.');return;}state.profile.statement=value('statement');state.onboarded=true;log('Local identity created','Identity');}persist();navigate(step===4?state.status==='ACTIVE'?'me':'path':'identity'+(step+1));return;}
    if(type==='privacy'){state.privacy=value('privacy');persist();navigate('me');toast('Local privacy preference saved.');return;}
    if(type==='memory'){if(!requireActive())return;if(!value('title')||!value('date'))return;if(storyFile===false){toast('Choose a supported image under 1 MB.');return;}const file=form.querySelector('[type=file]').files[0];if(file&&storyFile===null){toast('Wait for your photo to finish loading.');return;}let video=value('video');if(video&&!/^https?:\/\//i.test(video)){toast('Use an https or http video link.');return;}const m={id:uid(),title:value('title'),text:value('text'),type:file?'photo':value('type'),by:state.actor,at:new Date(value('date')+'T12:00:00').toISOString(),image:storyFile||'',video};if(data.has('anchor')){if(!crypto.subtle){toast('Content proof requires localhost or HTTPS.');return;}const bytes=new TextEncoder().encode(JSON.stringify(m));m.hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');}state.memories.push(m);if(m.hash){log('Memory content hash computed','Story');state.proofs[0].hash=m.hash;}persist();closeModal();navigate('story');toast('A little piece of today, saved.');return;}
    if(type==='vow'){if(!requireActive())return;const text=value('text');if(!text){toast('Write something true.');return;}state.vows.push({id:uid(),text,by:state.actor,at:today(),status:'PENDING'});log('Vow proposed','Vow');persist();closeModal();render();toast('Waiting for '+other()+' to choose it too.');return;}
    if(type==='goal'){if(!requireActive())return;const target=Number(value('target'));if(!value('title')||!Number.isInteger(target)||target<1||target>1000000){toast('Enter a name and a valid target.');return;}state.goals.push({id:uid(),title:value('title'),text:value('text'),target,balance:{Alice:0,Sophie:0},image:'',spend:null});log('Shared goal created','Bond');persist();closeModal();render();return;}
    if(type==='deposit'||type==='spend'){const g=state.goals.find(g=>g.id===state.selectedGoal);if(!g||!requireActive())return;const amount=Number(value('amount'));if(!Number.isInteger(amount)||amount<1||amount>1000000){toast('Enter a whole amount from 1 to 1,000,000.');return;}if(type==='deposit'){g.balance[state.actor]+=amount;log('Demo contribution deposited','Bond');}else{if(g.spend){toast('This goal already has a pending spending request.');return;}if(amount>g.balance.Alice+g.balance.Sophie||!value('reason')){toast('Add a reason and an amount within your balance.');return;}g.spend={amount,reason:value('reason'),by:state.actor};log('Shared expense proposed','Bond');}persist();closeModal();render();return;}
    if(type==='order'){if(!requireActive()||!value('size'))return;state.orders.push({id:uid(),at:today(),kind:witnessType==='physical'?'Physical Ring':'Memory Object',material:state.material,size:value('size'),engraving:value('engraving')});persist();navigate('collection');toast('Design draft saved. No order was submitted.');}
  });
  document.addEventListener('input',e=>{if(e.target.name==='statement'){const el=document.querySelector('#statement-count');if(el)el.textContent=e.target.value.length+' / 200';}});
  document.addEventListener('change',e=>{if(e.target.id!=='f-image')return;const file=e.target.files[0],status=document.querySelector('#file-status');storyFile=null;if(!file){status.textContent='';return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1024*1024){storyFile=false;status.textContent='Choose a JPEG, PNG or WebP image under 1 MB.';return;}status.textContent='Loading photo…';const reader=new FileReader();reader.onload=()=>{storyFile=String(reader.result);status.textContent='Photo ready.';};reader.onerror=()=>{storyFile=false;status.textContent='Could not read this photo.';};reader.readAsDataURL(file);});
  document.querySelector('#actor-toggle').addEventListener('click',()=>{state.actor=other();persist();if(state.status==='INVITED')navigate(state.actor===state.invitation.to?'received':'sent');else{render();toast('Acting as '+state.actor+' in the local demo.');}});
  window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'gateway';render();app.focus({preventScroll:true});});
  window.addEventListener('storage',e=>{if(e.key!==KEY||!e.newValue)return;try{const next=JSON.parse(e.newValue);if(validSession(next)){const actor=state.actor;state=next;state.archives??=[];state.actor=actor;render();}else toast('The changed local session is invalid.');}catch{toast('Could not load the changed local session.');}});
  setInterval(()=>{const el=document.querySelector('#countdown');if(el){el.textContent=countdown();if(state.invitation&&Date.now()>=new Date(state.invitation.expires).getTime())render();}},1000);
  render();if(saveWarning)toast('Local persistence is unavailable.');
})();
